### ISSUE TITLE
Arbitrary counts column in cooler file. 

### ISSUE THREAD

**Issue by aakashsur** [mirnylab/cooler#101]
From what I gather, if my initial count data looked like this:

Chr1             Pos1             Chr2             Pos2             Count
hg38_chr1   124478180   hg38_chr1   121966400   1
hg38_chr1   124478180   hg38_chr1   121760000   10

My understanding of going through these steps:
```
cooler makebins chrom.size resolution > file.bed
cooler csort -p 1 -c1 1 -p1 2 -c2 3 -p2 4 -o counts.sorted counts.txt chrom.sizes
cooler cload pairix -p 1 file.bed counts.sorted counts.cool
cooler zoomify -p 1 --balance --out counts.mcool counts.cool
```
would not incorporate the counts column at all. I have some pre-balanced data I wanted to visualize so there were non-integer counts, and I also wanted to visualize p-values per bin pair. However I'm not sure how to incorporate the counts column in the cool (and eventually mcool) file. 

Is the only way to load counts to use the cooler load and use the COO-rdinate matrix format?

**Comment by nvictus** [comment]
You should be able to use `cooler load` and the bg2 (2D bedGraph) format. That is almost identical to what you have, but includes the `end` coordinates of the bins, and is sorted and indexed with pairix. If your count column is non-integer, you can pass in the option `--count-as-float`.

**Comment by aakashsur** [comment]
Got it, awesome thanks!
