### ISSUE TITLE
Syntax for zoomify --balance-args

### ISSUE THREAD

**Issue by aakashsur** [mirnylab/cooler#102]
Hi, I tried `cooler zoomify -p 1 --balance --balance-args='cis-only,min-nnz=40' --out counts.mcool counts.cool` and it doesn't throw an error but it doesn't seem to have recorded an ICE transformation in the .mcool file. I'm assuming that my syntax is wrong?

**Comment by sergpolly** [comment]
Please try following:
`cooler zoomify -p 1 --balance --balance-args='--cis-only --min-nnz 40' --out counts.mcool counts.cool`


`--balance-args` expects arguments/options from user in the same exact format, as one would use to run command line version of `cooler balance` itself.

**Comment by aakashsur** [comment]
Got it, not sure why I didn't try that... I did what you have without the quotes and it failed for obvious reasons.

**Comment by sergpolly** [comment]
glad it helped! I don't even know if it's documented? @nvictus ?

**Comment by aakashsur** [comment]
It's a little ambiguous in the documentation/man page. Here's what it currently has (minus the other flags): 
```
Usage: cooler zoomify [OPTIONS] COOL_PATH
--balance-args TEXT       Additional arguments to pass to cooler balance
```
