### ISSUE TITLE
[Bug] Error after update from version 0.7.6 to 0.7.9

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#116]
Hello cooler-Team,

I just updated from version 0.7.6 to 0.7.9. I get now the following error:

`
File "/home/wolffj/miniconda2/envs/__hicexplorer@2.1.1/lib/python2.7/site-packages/hicexplorer/hicTransform.py", line 156, in main
|  hic_ma.save(path + basename_obs_exp, pSymmetric=False, pApplyCorrection=False)
|  File "/home/wolffj/miniconda2/envs/__hicexplorer@2.1.1/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1495, in save
|  self.save_cooler(pMatrixName, pSymmetric=pSymmetric, pApplyCorrection=pApplyCorrection)
|  File "/home/wolffj/miniconda2/envs/__hicexplorer@2.1.1/lib/python2.7/site-packages/hicexplorer/HiCMatrix.py", line 1367, in save_cooler
|  append=False)
|  File "/home/wolffj/miniconda2/envs/__hicexplorer@2.1.1/lib/python2.7/site-packages/cooler/io.py", line 286, in create
|  file_path, target, meta.columns, iterable, h5opts, lock)
|  File "/home/wolffj/miniconda2/envs/__hicexplorer@2.1.1/lib/python2.7/site-packages/cooler/_writer.py", line 203, in write_pixels
|  for i, chunk in enumerate(iterable):
|  File "/home/wolffj/miniconda2/envs/__hicexplorer@2.1.1/lib/python2.7/site-packages/cooler/_binning.py", line 1358, in _validate_pixels
|  raise BadInputError("Found bin1_id greater than bin2_id")
|  cooler._binning.BadInputError: Found bin1_id greater than bin2_id
`

Have you changed anything in the way how `cooler.io.create` works? I am using it in this way:
`
cooler.io.create(cool_uri=pFileName,
                             bins=bins_data_frame,
                             pixels=matrix_data_frame,
                             append=False)
`

With version 0.7.6 this was working well. 

Thanks for your help.

**Comment by nvictus** [comment]
I've added stricter input validation. Is `matrix_data_frame` lex-sorted by `bin1_id` then `bin2_id`?

**Comment by nvictus** [comment]
Let me know if it still complains after passing in `matrix_data_frame.sort_values(['bin1_id', 'bin2_id'])`.

Btw, for more general cases, there are now input sanitizers you can use, depending on your input dataframe: [sanitize_records](http://cooler.readthedocs.io/en/latest/api.html#cooler.io.sanitize_records) if your input is in genomic coordinates and you haven't assigned bin IDs to it, or [sanitize_pixels](http://cooler.readthedocs.io/en/latest/api.html#cooler.io.sanitize_pixels) if the bin IDs are already assigned. Sanitizers basically do mate "flipping", bounds checking, sorting, and bin assignment in the former case.

If your input is really large, you can also break it up into dataframe chunks and load them in any order by using `create_from_unordered()`. This has been used to implement `cooler cload pairs` and `cooler load`, which can now accept streaming input. This was all part of trying to make creation more flexible and less error prone. We should eventually consolidate these into a higher level create API that does input sanitization automatically.

**Comment by joachimwolff** [comment]
Thanks.
