### ISSUE TITLE
flip strip() missing?

### ISSUE THREAD

**Issue by NoamKaplan** [mirnylab/cooler#121]
Hi guys,

In `cooler/cli/csort.py`, in the flipping code there is no `strip()` when reading lines from the instream:

`parts = line.split(b"{sep}")`

So the last element of `parts` has a newline, and if the line is flipped the newline is moved to the middle of the line and the file gets messed up. I think it should be:

`parts = line.strip().split(b"{sep}")`

Best

Noam

**Comment by NoamKaplan** [comment]
Oh, and don't forget to add back the newline later:

`outstream.write(b"\\t".join(parts)+b"\\n")`

**Comment by nvictus** [comment]
Thanks, Noam! You're completely right. I'm surprised this never got caught till now, but I guess we've never used csort on a file where a position column was in last place and required flipping! Fix will be in the next release.
