### ISSUE TITLE
Can't find cooler file after loading in data

### ISSUE THREAD

**Issue by daniellenguyen** [mirnylab/cooler#127]
I used this command:

`cooler load -f coo chromsizes.tsv:1 output.tsv matrix.cool --count-as-float`

but afterwards no matrix.cool file appeared in my current directory or anywhere on my machine. 
Here is the file I tried to convert: [output.tsv](https://drive.google.com/file/d/1ek1s66n5VZTWHhHFZQayQcRa6cP3hMRN/view?usp=sharing)

Thanks in advance!

**Comment by nvictus** [comment]
Shoot.. however, there is a new issue with dtype conversion via cooler load, so the floating point data from your input file loaded as integers. I'll push a fix now.

**Comment by nvictus** [comment]
Fixed in 0.7.11

`cooler load -f coo --count-as-float --tril-action drop chromsizes.tsv:1 output.tsv matrix.cool `

**Comment by daniellenguyen** [comment]
Thank you!

**Comment by gtrichard** [comment]
I have the same issue in 0.7.11, I used the following command on [this matrix](https://drive.google.com/open?id=1uTB23lDEms9h2171WT617r7uZfSvOTBl):

```
cooler load -f bg2 --count-as-float --assembly dm6 --tril-action drop dmel.chrom.size:1000 matrix.bg2.gz matrix.1000.cool
```

Then I receive this error:

```
(...)
raise BadInputError("Found duplicate pixels:\n{}".format(err.to_csv(sep='\t')))
cooler._binning.BadInputError: Found duplicate pixels:
	chrom1	start1	end1	chrom2	start2	end2	count	bin1_id	bin2_id
1	2L	5035	5663	2L	5663	6452	99.1326506896	5	5
121	2L	5663	6452	2L	6452	7307	71.7622065951	5	6
122	2L	5663	6452	2L	7307	8134	66.3572702391	5	7
5	2L	5035	5663	2L	8674	9245	32.3981584924	5	8
123	2L	5663	6452	2L	8134	8674	59.765679643	5	8
(...)
```

**Comment by nvictus** [comment]
It looks like there's a mismatch between the matrix you're asking for (1kb resolution) and the one you are providing... it looks like it might be restriction fragment-delimited? You would have to provide a bed file with the bin segmentation that was used.

If your goal was to aggregate that matrix to 1kb, then try `cooler cload pairs`:

```
cooler cload pairs --assembly dm6 --tril-action drop dm6.chrom.sizes:1000 matrix.bg2.gz matrix.1000.cool -c1 1 -p1 2 -c2 4 -p2 5
```

I used the following chrom sizes and it worked:

```
2L	23513712
2R	25286936
3L	28110227
3R	32079331
4	1348131
X	23542271
Y	3667352
```

**Comment by gtrichard** [comment]
Yes the matrix is fragment-delimited. Oh ok I get it now for the bin segmentation, thank you! Maybe I did not check the documentation thoroughly enough and missed it.

My goal is to display the matrix in HiGlass, so one solution is to use your suggested command-line to aggregate the matrix to the median bin size, and then `cooler zoomify` it for HiGlass. I tested it and it works perfectly.

**Comment by nvictus** [comment]
Awesome!

Yeah, if your goal is to display it in HiGlass, for now it needs to have a fixed bin size. Glad it worked.
