### ISSUE TITLE
Cooler zoomify converts float counts to int

### ISSUE THREAD

**Issue by pkerpedjiev** [mirnylab/cooler#129]
If run `cooler zoomify matrix.cool` on a matrix which has float pixel counts, the resulting multires matrix has integer pixel counts. What gives?

![image](https://user-images.githubusercontent.com/2143629/44303221-08a71180-a309-11e8-9a9c-e58e7dda322d.png)

Matrix can be found here: https://www.dropbox.com/s/fc7jcqd8455c692/matrix.cool?dl=0

(Tangentially related to https://github.com/mirnylab/cooler/issues/127)

**Comment by nvictus** [comment]
Fixed in 0.8
