### ISSUE TITLE
switch from absolute tolerance to relative?

### ISSUE THREAD

**Issue by golobor** [mirnylab/cooler#131]
according to [the code](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L135), currently, tolerance is specified in the units of #contacts.

An attempt to trace units:
[line 135](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L135): margs are in the units of #contacts (i.e. proportional to # of reads in the library)
[line 145](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L145): nzmargs are in the units of margs (#contacts)
[line 156](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L156): var in the units of nzmargs (#contacts)
[line 167](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L167): tol is compared to var

importantly, [margs are re-computed using biases](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L139), but [biases average out to 1.0](https://github.com/mirnylab/cooler/blob/master/cooler/ice.py#L154), so margs first come out in the units of #contacts

Specifying tol in relative units makes more sense since it is hard for the user to know the # of reads in the library before balancing. We can still keep the option to specify an absolute tolerance, but I would argue that relative tolerance is a better default.

**Comment by golobor** [comment]
bump?

**Comment by golobor** [comment]
bump

**Comment by nvictus** [comment]
See #210
