### ISSUE TITLE
calculate cis/total during balancing and use it to filter rows

### ISSUE THREAD

**Issue by golobor** [mirnylab/cooler#134]
A major practical issue with processing Hi-C data is the presence of genomic translocations. They lead errors into the calculated genomic distances and confuse cis contacts with trans ones, thus breaking the expectations of downstream analyses (obs/exp, eigenvectors).
Historically, @mimakaev and @gfudenberg dealt with these issues by filtering out genomic bins that form an untypically high fraction of trans contacts. Recently, @Phlya pointed out the need for such filters in cooler.
A simple suggestion would be to calculate the cis/total fraction in raw bins (cis_tot_raw), detect low-value outliers using MADmax and filter them out (on top of the already used MADmax-coverage filter).It may also be useful to report both the cis_tot_raw and cis_tot_balanced (i.e. cis/total fraction after filtering/balancing).

**Comment by Phlya** [comment]
Also intra-chromosomal translocations, which can, probably, be filtered similarly, but by long-range cis over total cis, or over short range cis.

**Comment by gfudenberg** [comment]
Since cis/total has a broad, locus-dependent, range influenced by mant
factors, I've found that filtering on whether a bin has any extreme
trans-values  (e.g. equivalent to third cis diagonal) can be useful in
addition to just filtering on cis/total.

**Comment by gfudenberg** [comment]
bumping this-- @golobor suggests that cis & total sums can be set as columns during balancing

**Comment by nvictus** [comment]
See #210
