### ISSUE TITLE
allow csort to take multiple pairs files

### ISSUE THREAD

**Issue by golobor** [mirnylab/cooler#15]
It would be very useful to allow csort to take multiple pair files at the same time and merge them into the same sorted (and, optionally, de-duped) output file. This would allow to merge multiple lanes of the same replica or multiple replicas into the same condition.

**Comment by nvictus** [comment]
For pairs, this is solved by pairsamtools merge. For binning, this is solved by loading each pairs file into a separate cooler and then using `cooler merge`. Re-open if I'm missing something.
