### ISSUE TITLE
what‘s cooler’s URI and how to obtain it ?

### ISSUE THREAD

**Issue by sunhaifeng123** [mirnylab/cooler#152]
what‘s cooler’s URI and how to obtain it ?

I gained a file chr1.cool  and run : 

cooler info chr1.cool
{
    "nbins": 54521,
    "bin-type": "fixed",
    "format": "HDF5::Cooler",
    "sum": 1466014,
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 2,
    "genome-assembly": "unknown",
    "creation-date": "2019-02-19T13:22:09.700700",
    "generated-by": "cooler-0.7.11",
    "nnz": 743172,
    "nchroms": 22,
    "bin-size": 50000
}

The next analysis need use this chr1.cool's URI , but I really don't know how to obtain this URI.

Can anyone help me ? really thanks very much!!!

Haifeng Sun
2019-02-20

**Comment by nvictus** [comment]
For a single-resolution cooler file, the URI is just the file path. For multi-cooler files, the URI is the file path followed by `::` followed by the internal group path to the root of a data collection. To see the internal structure of a file,  use `cooler tree`. For more info, see the [docs](https://cooler.readthedocs.io/en/latest/schema.html#data-collection).
