### ISSUE TITLE
what kind of dict should be used in create_cooler

### ISSUE THREAD

**Issue by zhqu1148980644** [mirnylab/cooler#156]
`pixels={"bin1_id": 1, "bin2_id": 2 , "count" : 100}`
The above one doesn't fit `cooler.create_cooler`

**Comment by nvictus** [comment]
Use arrays or lists to define columns. Something functionally equivalent to a data frame.

`pixels={"bin1_id": [1], "bin2_id": [2] , "count" : [100]}`

**Comment by zhqu1148980644** [comment]
thanks
