### ISSUE TITLE
cooler cload pairs : Cannot find a pair reads file for GSE63525 HUVEC

### ISSUE THREAD

**Issue by kabhel** [mirnylab/cooler#157]
Hello,

I would like to create a `.cool` format file from **GSE63525 HUVEC** (Rao et al).

Thus, I'm trying to find a read pairs file containing the chr1, pos1, chr2 and pos2 fields in order to run the following command : `cooler cload pairs -c1 INT -p1 INT -c2 INT -p2 INT BIN PAIRS_FILE OUTPUT_FILE`

I tried to find a pair reads file among the files listed by GEO. However, I cannot find one which could correspond (or I don't know which of them I can use).
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63525

```
GSE63525_HUVEC_Arrowhead_domainlist.txt.gz
GSE63525_HUVEC_HiCCUPS_looplist.txt.gz
GSE63525_HUVEC_HiCCUPS_looplist_with_motifs.txt.gz
GSE63525_HUVEC_combined.hic.gz
GSE63525_HUVEC_combined_30.hic.gz
GSE63525_HUVEC_interchromosomal_contact_matrices.tar.gz
GSE63525_HUVEC_intrachromosomal_contact_matrices.tar.gz
```

For the example given in the Jupyter-notebook, the pair reads file was provided by GEO under `*_merged_nodups.txt.gz` name.

Can someone help please?

Helene

**Comment by nvictus** [comment]
None of those are read pairs files, unfortunately. You have a few options:
* Un-gzip and convert the hic files using [hic2cool](https://github.com/4dn-dcic/hic2cool)
* Un-tar the contact matrix text files and load them using `cooler load`. You will have to modify them to conform to either the COO or BG2 formats described in the [docs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-load). For example, you can load each intra/inter chromosomal matrix separately as BG2 and merge them together with `cooler merge`.

We also re-mapped those datasets a long time ago and you can find coolers here: ftp://cooler.csail.mit.edu/coolers/hg19/
