### ISSUE TITLE
How to convert the contact pairs into cool? 

### ISSUE THREAD

**Issue by yancychy** [mirnylab/cooler#159]
Hi, 
My data file is like this format:  
chr21 28000001 28030000 chr21 28030001 28060000 828.761726915523
chr21 28000001 28030000 chr21 28060001 28090000 1174.46200449397
chr21 28000001 28030000 chr21 28090001 28120000 799.700568963159
chr21 28000001 28030000 chr21 28120001 28150000 1087.62401591727
chr21 28000001 28030000 chr21 28150001 28180000 971.819942170359
chr21 28000001 28030000 chr21 28180001 28210000 853.160008439214

I used the command:

cooler cload pairs -c1 1 -p1 2 -c2 4 -p2 5 hg38.chrom.sizes:30000 IMR90_chr21-28-30Mb.txt out3180.cool 

cooler zoomify --blance out3180.cool

 higlass-manage ingest ~/Documents/HiC/zhuang/hic/out3180.mcool

But the higlass show a black figure. It seems that all value is 0. 

I also tried to use another command but failed: 

cooler load -f bg2 hg38.chrom.sizes:30000 IMR90_chr21-28-30Mb.txt mycooler.cool

  File "pandas/_libs/parsers.pyx", line 1156, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe' 

Is there any error in my command? 

Thanks.

**Comment by nvictus** [comment]
`cooler cload pairs` aggregates each pairs record as a single count. Your input looks like a binned matrix, not pairs, right? 

In that case you want to use [cooler load](https://cooler.readthedocs.io/en/latest/cli.html#cooler-load). The input format is "2D bedGraph"-style, so use `-f bg2`. Additionally, your start coordinates are one-based so you should also pass `--one-based` and your values are floating point, so you should also pass `--field count:dtype=float`. Not having this last one is probably the source of the error you got.

**Comment by yancychy** [comment]
Thanks nvictus. Yes, it's matrix file not pairs. I got the right results under your suggestions. 
But the  --field command shows errors: 
cooler load -f bg2 --field count:dtype=float --one-based --count-as-float hg38.chrom.sizes:30000 IMR90_chr21-28-30Mb_3180_.txt mycooler.cool 
Usage: cooler load [OPTIONS] BINS_PATH PIXELS_PATH COOL_PATH 
Error: Invalid value: Expected '--field {name},{number}' or '--field {name},{number},{dtype}'; got 'count:dtype=float'

Another change:
cooler load -f bg2 --field {count},{6},{float} --one-based --count-as-float hg38.chrom.sizes:30000 IMR90_chr21-28-30Mb_3180_.txt mycooler.cool 

Traceback (most recent call last):
  File "/usr/local/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cooler/cli/load.py", line 267, in load
    extra_fields = _parse_field_params(field)
  File "/usr/local/lib/python3.7/site-packages/cooler/cli/load.py", line 36, in _parse_field_params
    if number < 0:
UnboundLocalError: local variable 'number' referenced before assignment 


I tried to simplify the command as following. It works: 
cooler load -f bg2  --one-based --count-as-float hg38.chrom.sizes:30000 IMR90_chr21-28-30Mb_3180_.txt mycooler.cool  
cooler zoomify --balance mycooler.cool 
higlass-manage ingest ~/Documents/HiC/mycooler.cool

**Comment by nvictus** [comment]
Ah, you must be using a 0.7 version? The syntax for the `--field` option changed in the latest version.

The `{}` braces were meant to symbolize placeholder names... it might have worked if you omitted them: `--field count,7,float` (the field numbers are specified as one-based). In any case, `--count-as-float` works too.

**Comment by yancychy** [comment]
oh, yes, my version is cooler, version 0.7.10. I thought the docker will update it to the newest version. 
Thanks.
