### ISSUE TITLE
Writing cooler object to a file with python API

### ISSUE THREAD

**Issue by machinegun** [mirnylab/cooler#162]
Hi,

Is there any way I can write a Cooler object to a .cooler file using your python API?

Jay

**Comment by nvictus** [comment]
Hi Jay,

Technically, a `Cooler` Python object is an interface to a location in an existing file (a data collection), so there is nothing to write.

You can copy a data collection in one file to another file, or even to a different path within the same file. There are some convenience functions in [`cooler.fileops`](https://cooler.readthedocs.io/en/latest/api.html#cooler.create_cooler), and there are `cp`, `mv` and `ln` [commands](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cp) in the CLI. But, note that it is also trivial to perform these operations just using [`h5py`](http://docs.h5py.org/en/stable/high/group.html).

If your question is about reading/generating data in memory and/or making modifications, and writing out to a new file, check out the [`create_cooler`](https://cooler.readthedocs.io/en/latest/api.html#cooler.create_cooler) function. It takes a data frame of pixels as input (or an iterator thereof).

**Comment by machinegun** [comment]
Thanks!
