### ISSUE TITLE
Error message appeared when balancing the cool file

### ISSUE THREAD

**Issue by weiwang2626** [mirnylab/cooler#168]
Hi there,
I generated my .mcool file by following the tutorial: https://hms-dbmi.github.io/hic-data-analysis-bootcamp/#21. Everything went well except when I came to the balancing step, I got an error message as in the attached screenshot. Could anybody help me solve this problem? Since the final .mcool file was generated anyway, could I still use it to submit to HiGlass, or I have to fix this problem to get the correct matrix plot?
Thank you in advance!
Wei
![Untitled](https://user-images.githubusercontent.com/37217346/59220676-820f3980-8b93-11e9-8714-6930dab41699.png)

**Comment by Phlya** [comment]
This means the balancing procedure didn't converge. It probably means that you don't have enough data for this in the cool file. You can still visualize the mcool file in HiGlass, but without balancing the data will not look like it should.
More information about your data would help, i.e. how many contacts do you have in the cool file?

**Comment by weiwang2626** [comment]
Hi Phlya, I truly appreciate your reply. I was just about to report that I figured the problem. It is actually due to the low resolution I set before. When I reduced the resolution from 500000 to 1000, the balancing executed without any problem. Thanks again.

**Comment by Phlya** [comment]
Glad the problem is solved, although I have to say that normally bigger binsizes are easier to balance than small ones, so that's actually strange....
