### ISSUE TITLE
requirements.txt very out of date

### ISSUE THREAD

**Issue by keiranmraine** [mirnylab/cooler#169]
I discovered this as I tend to install things with pip via:

```
pip install -r requirements.txt
python setup.py install
```

Trying to use as above fails with a clean virtualenv (py3.6)

**Comment by nvictus** [comment]
Thanks for pointing that out! I haven't kept it up to date because I use conda environments, and tend to install some things with conda and others with pip. Will update.

**Comment by nvictus** [comment]
I've added a loose `requirements.in` and updated the pinned `requirements.txt`
