### ISSUE TITLE
cload - UserWarning: Did not find contig  'chr1' in contact list file

### ISSUE THREAD

**Issue by keiranmraine** [mirnylab/cooler#170]
I'm using `cload` with the bin shortcut options as follows:

```
cooler cload pairix -s 8 GRCh38.mainonly.chrom.size:1000 SAMPPLE.output.pairs.gz SAMPLE.output.cool
```

In the logs I'm seeing:

```
WARNING:py.warnings:/software/CGP/modules/installs/cooler/cooler-0.8.5/env/lib/python3.6/site-packages/cooler-0.8.5-py3.6.egg/cooler/create/_ingest.py:740: UserWarning: Did not find contig  'chr1' in contact list file.
  " '{}' in contact list file.".format(chrom))
...
```

The outputs all seem as I would expect.  Should this be suppressed?

**Comment by nvictus** [comment]
That warning just means that `SAMPLE.output.pairs.gz` did not contain any reads mapped to chr1 but chr1 was in your chromsizes. If this is indeed correct, then the warning can be ignored. If not, then that's strange...

The warning is especially useful for catching the case when the chromsizes uses a different chromosome naming convention than the pairs file.

**Comment by keiranmraine** [comment]
Ah, thanks.  Completely expected then as I was testing with a single chr.
