### ISSUE TITLE
Can not merge the replicate cool file simultaneously  with different resolution

### ISSUE THREAD

**Issue by Prayforhanluo** [mirnylab/cooler#176]
I have two replicate cool files
rep1.cool
rep2.cool
both with resolution 200000 and 40000
I can load with `cooler.Cooler(rep1.cool::200000)` or `cooler.Cooler(rep1.cool::40000)`
I use `cooler.merge_coolers` to merge replicates like:
```
    Merge_cool = 'Merge.cool'
    for res in [200000, 40000]:
        merge_cool = '{}::{}'.format(Merge_cool,res)
        replicate_cool = [‘{}::{}’.format(i,res) for i in ['rep1.cool','rep2.cool']]
        cooler.merge_coolers(output_uri = merge_cool,
                                       input_uris = replicate_cool,
                                       mergebuf = int(20e6) )
```
but finally my Merge_cool only has one resolution 40000 (last one)
I can load  `cooler.Cooler('Merge.cool::40000')`
I cant load  `cooler.Cooler('Merge.cool::200000')`
What should i do to merge repliecate cool file simultaneously  with different resolution

Thanks for any help

**Comment by Prayforhanluo** [comment]
@golobor

**Comment by golobor** [comment]
Hi,
it's not possible to merge coolers with different resolution, as this operation is not well-defined. 
What you could do, though, is to coarsen the 20kb cooler by a factor of 2 down to 40kb (https://cooler.readthedocs.io/en/latest/cli.html#cooler-coarsen) and merge the result with the other 40kb cooler.
Anton

**Comment by nvictus** [comment]
Actually, it looks like you are merging coolers of the same resolution, but you writing both to the same location. You need to use separate output URIs (`Merge.cool::40000`, `Merge.cool::200000`) for the two resolutions if you want both in the same file.

**Comment by nvictus** [comment]
Ah, right... the problem is that the default write mode is `"w"`, so subsequent merges truncate the file. Delete Merge.cool and retry with adding `mode="a"` to `cooler.merge_coolers()`.

**Comment by Prayforhanluo** [comment]
> Ah, right... the problem is that the default write mode is `"w"`, so subsequent merges truncate the file. Delete Merge.cool and retry with adding `mode="a"` to `cooler.merge_coolers()`.

I got it. Thanks a lot.
