### ISSUE TITLE
C++ support?

### ISSUE THREAD

**Issue by anlin00007** [mirnylab/cooler#177]
Hello,

I am trying to add cooler format into input type list for my tool. As my tool is written in C++, I am wondering if there is an example code for reading cooler files with C++? 

Thanks
Lin

**Comment by nvictus** [comment]
Unfortunately, we don't have an example yet. I have never used HDF5 from C++, but this [guide](https://portal.hdfgroup.org/display/HDF5/Learning+the+Basics) should help. With C++, you should be able to use either use the native C API or the C++ wrapper.

If you simply want to load the any of the tables (`chroms`, `bins` or `pixels`) from a file, you'll need to (1) open the file, (2) open the datasets (i.e. arrays) corresponding to the columns of the table you want, e.g. to load the pixel table of a 10kb resolution heatmap in a mcool, you'll need to access datasets `/resolutions/10000/pixels/bin1_id`, `resolutions/10000/pixels/bin2_id` and `/resolutions/10000/pixels/count`.

For more complex queries, you'll want to access the indexes, described [here](https://cooler.readthedocs.io/en/latest/schema.html#indexes).

If you get a simple example working, please share!

**Comment by nvictus** [comment]
Oh, this project may be just what you want: https://github.com/BlueBrain/HighFive
