### ISSUE TITLE
Convert cool format to dense contact matrix

### ISSUE THREAD

**Issue by KunFang93** [mirnylab/cooler#178]
Hi, 

I was wondering if there is any way to convert .cool format to dense contact matrix for following analysis such as TopDom? Thanks a lot!

Best,
Kun

**Comment by nvictus** [comment]
You can use the [matrix selector](https://cooler.readthedocs.io/en/latest/concepts.html#matrix-selector) to retrieve dense numpy arrays in Python. From there, you can output whatever dense format TopDom needs. e.g. [np.savetxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html), or [np.save](https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html#numpy.save).

Cooltools also has a command line tool [dump-cworld](https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/dump_cworld.py) to output the dense text format used by the Dekker lab's C-world tools, which might be what you want (tab-separated).

**Comment by KunFang93** [comment]
Understand~Thanks a lot!
