### ISSUE TITLE
Balanced value different from weights value

### ISSUE THREAD

**Issue by KunFang93** [mirnylab/cooler#182]
Hi,

I was confused when I use Table selector. I was not sure what is difference between "weights" and "balanced" and why the counts values are different when I use two different codes?

When I use _c.bins().fetch('1')[:10]_, the results are
chrom   start      end    weight
0     1       0   100000       NaN
1     1  100000   200000       NaN
2     1  200000   300000       NaN
3     1  300000   400000       NaN
4     1  400000   500000       NaN
5     1  500000   600000       NaN
6     1  600000   700000       NaN
7     1  700000   800000  0.147579
8     1  800000   900000  0.081024
9     1  900000  1000000  0.143122
however, when I use _c.matrix(as_pixels=True,join=True).fetch('1')[:10]_ ,the results are
 chrom1  start1    end1 chrom2     start2       end2  count  balanced
0      1       0  100000      1          0     100000      6       NaN
1      1  100000  200000      1     100000     200000      1       NaN
2      1  200000  300000      1     200000     300000      4       NaN
3      1  500000  600000      1     500000     600000     98       NaN
4      1  500000  600000      1    4700000    4800000      1       NaN
5      1  500000  600000      1    8100000    8200000      1       NaN
6      1  500000  600000      1   66900000   67000000      1       NaN
7      1  500000  600000      1   74800000   74900000      1       NaN
8      1  500000  600000      1  109300000  109400000      1       NaN
9      1  500000  600000      1  249000000  249100000      1       NaN

I was wondering what are differences between those "balanced" values and "weights" values?

Besides, I was also confused about the count number/
when I use _c.pixels().fetch('1')[:10]_, the results are 
bin1_id  bin2_id  count
0        0        0      6
1        0     6067      1
2        0     8831      1
3        0    14364      1
4        0    23413      1
5        0    26605      1
6        1        1      1
7        1     8126      1
8        1    17436      1
9        2        2      4
while the count numbers in _c.matrix(as_pixels=True,join=True).fetch('1')[:10]_ are
chrom1  start1    end1 chrom2     start2       end2  count  balanced
0      1       0  100000      1          0     100000      6       NaN
1      1  100000  200000      1     100000     200000      1       NaN
2      1  200000  300000      1     200000     300000      4       NaN
3      1  500000  600000      1     500000     600000     98       NaN
4      1  500000  600000      1    4700000    4800000      1       NaN
5      1  500000  600000      1    8100000    8200000      1       NaN
6      1  500000  600000      1   66900000   67000000      1       NaN
7      1  500000  600000      1   74800000   74900000      1       NaN
8      1  500000  600000      1  109300000  109400000      1       NaN
9      1  500000  600000      1  249000000  249100000      1       NaN

I was wondering why these two codes get different number of counts.

Thanks a lot!
Best,
Kun

**Comment by nvictus** [comment]
>  what is difference between "weights" and "balanced" 

A unique `weight` is assigned to each **bin**. A **pixel** inherits a `weight1` and `weight2` from its corresponding bin1 and bin2, respectively, and a `count` value. The `balanced` column contains the calculated value `count * weight1 * weight2` for each pixel.

> When I use c.bins().fetch('1')[:10], the results are

`c.bins()` will query the **bin** table, not pixels. Think of it as an "axis" of the matrix. See the description [here](https://cooler.readthedocs.io/en/latest/datamodel.html#bins).

>  when I use c.pixels().fetch('1')[:10], the results are

`c.pixels()` will query the pixel table. However, this selector doesn't understand 2D range queries. The `fetch` method interprets queries as slices along the bin1 axis (i.e. slices of full rows), so the output will also contain **trans** values.

I believe this fetch behavior for the pixel selector is not well documented, so we should probably fix that.

>  c.matrix(as_pixels=True,join=True).fetch('1')[:10]

`c.matrix()` is a 2D selector on pixels. The `fetch` method can take 2 arguments and `fetch('1')` is equivalent to `fetch('1', '1')`. The output does not contain any trans values in this case.

Does that make sense?

**Comment by KunFang93** [comment]
Thanks a lot for your prompt reply! 

If I understand correctly, the balanced value is the final normalized value, right? If I want to do down-stream analysis like call TADs or compartment, for example, calling TADs on chr1, I could use c.matrix().fetch('1') as the dense contact matrix? 

Other thing confused me is I am not clear whether this balanced process is doing within chromosome or also consider other chromosomes. For example, if I use _c.matrix(as_pixels=True,join=True).fetch('1')[:]_, the results are:
    chrom1     start1       end1 chrom2     start2       end2  count  balanced
0           1          0     100000      1          0     100000      6       NaN
1           1     100000     200000      1     100000     200000      1       NaN
2           1     200000     300000      1     200000     300000      4       NaN
3           1     500000     600000      1     500000     600000     98       NaN
4           1     500000     600000      1    4700000    4800000      1       NaN
...       ...        ...        ...    ...        ...        ...    ...       ...
147011      1  249000000  249100000      1  249000000  249100000    106  3.544801
147012      1  249000000  249100000      1  249100000  249200000      2  0.021134
147013      1  249100000  249200000      1  249100000  249200000    242  0.808036
147014      1  249100000  249200000      1  249200000  249250621      5       NaN
147015      1  249200000  249250621      1  249200000  249250621     63       NaN

I noticed that line4 has count value 98 but balanced value is NAN while line 147012 have count value 2 but balanced value 0.02. Also line 147011 with small count value(106) than line 147013 (242) but has higher balanced value. Shouldn't the balanced value be positive correlated with balanced value? 

Thanks a lot!

**Comment by nvictus** [comment]
> If I understand correctly, the balanced value is the final normalized value, right?

That's right.

> Shouldn't the balanced value be positive correlated with balanced value?

Consider the formula: `weight1 * weight2 * count`, or in different notation, `w[i] * w[j] * A[i, j]`. For each pixel, the outcome is going to depend on contributions of the two bins `i` and `j`. Also, if a bin gets filtered out for poor coverage during balancing, it is assigned a weight value of `NaN`, so all nonzero pixels along that row or column become NaN. When using the dense matrix selector (the default `c.matrix()`), the entire row/column corresponding to each filtered bin will be set to NaN.

>  If I want to do down-stream analysis like call TADs or compartment, for example, calling TADs on chr1, I could use c.matrix().fetch('1') as the dense contact matrix?

Yes, that's right. Be mindful of the NaN values, though.

For more details on balancing (a.k.a. iterative correction), check out the IC [paper](https://www.nature.com/articles/nmeth.2148) and the [supplement](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/36/1/10.1093_bioinformatics_btz540/1/btz540_supplementary_materials.zip?Expires=1582191424&Signature=EezntVg0SjNx1o0dJrzJEV5kVlcSneMHvUWZUXCz0RejLWnSHPbeqfnB9zvl4r~SH8M72CoNuVWDD6PlLTFWAFG3AAiBoZSbOan36-uBIXB3HTEInJA0H8wFl3~~9ksT0r-CTE5GmFyeRJHeGkgCpOaL5a-6psVRvpLZl4qeZE1qxIcWs6CzkMNfVZu9ONxM~aT3OXkTpJxOw8Gdsq-LmilpzJleFAXOI9dBo7ufMKf9d-quiueO0zxeaMfevl6xw6KLsrTaF1uKI2BdwU2pc8q2wu3rGP-u4GHj2V4VLHpPvim8l2~8phLxtctAtp~8cdj1jhWolopm3qF6CBRQ-w__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA) to the cooler paper.

**Comment by KunFang93** [comment]
Thanks a lot for the explanation! That's make lots of sense~

But when I balance .cool file with small bin size. e.g. 40k, it cannot converge in the most cases with the following Error message:

...
...
INFO:cooler.balance:variance is nan
WARNING:py.warnings:balance.py:110:ConvergeneceWarning:Iteration limit reached without convergence.

ERROR:cooler.cli.balance:Iteration limit reached without convergence
ERROR:cooler.cli.balance:Storing final result. Check log to assess convergence.

I was wondering if this error comes from too many poor coverage bins and if there is a way to solve it? 

And if I would like to do the down-stream analysis, can I convert NAN to 0? 
Thanks again~

**Comment by nvictus** [comment]
> I was wondering if this error comes from too many poor coverage bins and if there is a way to solve it?

Poor coverage bins (rows/cols) are masked during balancing. That's what gives rise to the NaNs. And 40kb is not that small... How many reads are in your library?

> And if I would like to do the down-stream analysis, can I convert NAN to 0?

Depending what you are trying to do, yes, you can treat them as zeros, or you may want to leave out those rows/columns from your computations.
