### ISSUE TITLE
cooler digest fasta and fai same folder

### ISSUE THREAD

**Issue by rdacemel** [mirnylab/cooler#183]
Even though cooler digest ask to specify both files, it only runs if both of them are in the same directory.

**Comment by nvictus** [comment]
Hmm... where does it ask for the fai file? Maybe something was incorrectly documented.

It's using pyfaidx to read the fasta, which I think requires that the two be in the same folder. However, it will automatically generate the fai if it doesn't already exist.

**Comment by rdacemel** [comment]
I'm using cooler version 0.8.6 and this is the help message I got :/
```
Usage: cooler digest [OPTIONS] CHROMSIZES_PATH FASTA_PATH ENZYME
Try "cooler digest -h" for help.
```

**Comment by nvictus** [comment]
Maybe I misunderstood your question. Does the following type of invocation not work?

```
cooler digest /full/path/to/hg19.chrom.sizes.ordered /full/path/to/hg19.fasta DpnII > hg19.frags.bed
```

The fasta _index_ file `.fai` is not provided and assumed to be called `hg19.fasta.fai` and live in the same folder as the fasta file itself. If it doesn't already exist, pyfaidx will create one.

**Comment by rdacemel** [comment]
Hmmm I think that I was confusing fasta indexes with chromsizes, partially because they contain overlapping information. 
Perhaps it would be nice that to enable the option to run it without the chromsizes, only with the autocreated fasta index file, but I see the potential issues. Thanks!
