### ISSUE TITLE
Cooler load on bedpe: Error: Found duplicate pixels

### ISSUE THREAD

**Issue by docdot** [mirnylab/cooler#184]
Hi,

I'm trying to transform a bedpe file to cool file and I am receiving the following error

```
INFO:cooler.cli.load:fields: {'chrom1': 0, 'start1': 1, 'end1': 2, 'chrom2': 3, 'start2': 4, 'end2': 5, 'count': 6}
INFO:cooler.cli.load:dtypes: {'chrom1': <class 'str'>, 'start1': <class 'int'>, 'end1': <class 'int'>, 'chrom2': <class 'str'>, 'start2': <class 'int'>, 'end2': <class 'int'>, 'count': <class 'numpy.int32'>}
INFO:cooler.cli.load:symmetric-upper: True
INFO:cooler.create:Writing chunk 0: dir/tmpm430hpte.multi.cool::0
INFO:cooler.create:Creating cooler at "dir/tmpm430hpte.multi.cool::/0"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
Traceback (most recent call last):
  File "/usr/local/bin/cooler", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cooler/cli/load.py", line 309, in load
    h5opts=h5opts
  File "/usr/local/lib/python3.6/dist-packages/cooler/create/_create.py", line 649, in create_from_unordered
    columns=columns, dtypes=dtypes, mode='a', **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cooler/create/_create.py", line 577, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/usr/local/lib/python3.6/dist-packages/cooler/create/_create.py", line 213, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/usr/local/lib/python3.6/dist-packages/cooler/create/_ingest.py", line 307, in _validate_pixels
    raise BadInputError("Found duplicate pixels:\n{}".format(err.head().to_csv(sep='\t')))
cooler.create._ingest.BadInputError: Found duplicate pixels:
	chrom1	start1	end1	chrom2	start2	end2	count	bin1_id	bin2_id
57	chr1	929122	938714	chr1	995894	1002802	36	185	199
305	chr1	1884973	1895243	chr1	1939799	1947044	12	376	387
324	chr1	1939799	1947044	chr1	1948038	1956422	44	387	389
653	chr1	3244116	3251294	chr1	3292884	3302816	9	648	658
673	chr1	3354858	3358921	chr1	3362675	3374194	20	670	672


```

when I used the following command

`cooler load -f bg2 'bins_hg19/chrom_hg19_5000_bins.bed' dir/cooler_input_test.bedpe cooler_MYCN_test.cool`

I saw a similar error here
https://github.com/mirnylab/cooler/issues/127

I based my command on this thread 
https://github.com/mirnylab/cooler/issues/90

Even trying this command variation I receive the same error:

`cooler load -f bg2 --no-symmetric-upper 'bins_hg19/chrom_hg19_5000_bins.bed' dir/cooler_input_test.bedpe cooler_MYCN_test.cool`

I'm using cooler, version 0.8.6.post0

and my bedpe input head

```
chr1	50990	53158	chr1	62436	64259	10
chr1	535137	536378	chr1	3759279	3763882	38
chr1	612980	614248	chr1	4863530	4868352	25
chr1	711933	716177	chr1	753656	764405	21
chr1	711933	716177	chr1	929122	938714	2
chr1	711933	716177	chr1	1368960	1374377	13
chr1	723357	729461	chr1	796404	803458	10
chr1	753656	764405	chr1	766794	782079	53
chr1	753656	764405	chr1	787502	791270	23
chr1	753656	764405	chr1	871863	890954	31
```

Do you know what is going on?

Many thanks for your time,

Raphael

**Comment by docdot** [comment]
Hi,

More info, if I use higher bins resolutions -like 2500 and 500 bp, I don't get this error.
I believe that is due to the fact that some interactions are within two different bins, at the border.
However, the dataset is not sequenced this deeper to go at this resolution. 
I have to use at least 10 kb.

Is there any workaround this that does not involve to delete the interactions ID as duplicate pixels?

Please let me know as I'm struggling to sort this out.

Thanks

**Comment by nvictus** [comment]
Hmm... that looks like a fragment-delimited matrix. How was that BEDPE generated?

Are you trying to re-bin the fragment-binned data using a fixed resolution (e.g 10kb)? `cooler load` can't do that. Rebinning the counts between two incompatible genome segmentations is not a well defined procedure so we don't support it. The intervals in the BEDPE file should match entries in the bin table you provide.

If you do want to re-aggregate the input, you want to use [cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs) which aggregates point coordinates. Ideally use the 5' ends of the original read pairs if you have them. If not, you can cheat and use something like fragment midpoints (and add `--field count={the value column number}:agg=sum`), but this is not recommended.

Does that make sense?

**Comment by nvictus** [comment]
Sticky note: If my diagnosis is right, we should be catching incompatible inputs like this and report a helpful error.

**Comment by docdot** [comment]
Hi,

Thanks for your reply.

This bedpe was generated from hichipper (https://github.com/aryeelab/hichipper), I used for HiChIP peak calling. From the *interactions.all.mango output (chromosome1, start1, end1, chromosome2, start2, end2, PETs supporting the interaction, the adjusted P-value of the interaction). From there, I've just removed the P-value column to have a .bedpe (hichipper also has a bedpe output, but I needed to filter by the adjusted P-value of the interaction).

In light of this, do you think the best option is to use  cooler cload pairs?
Like this:

`cooler cload pairs --chrom1 1 --pos1 2 --chrom2 4 --pos2 5 'bins_hg19/chrom_hg19_5000_bins.bed' dir/cooler_input_test.bedpe cooler_MYCN_test.cool
`
input
```
head dir/cooler_input_test.bedpe

1	2	3	4	5	6	7
chr1	50990	53158	chr1	62436	64259	10
chr1	535137	536378	chr1	3759279	3763882	38
chr1	612980	614248	chr1	4863530	4868352	25

```
Best

**Comment by nvictus** [comment]
Oh, I see! Then yes, you could use the peak midpoints with cload pairs. Depending on what you want, there is an option to tell it to sum values from the supported PETs column instead of treating each peak as a single point (`--field count=7:agg=sum`).

However, this isn't exactly the use case for cooler. Your file is really a peak annotation dataset. e.g., if you are using HiGlass, I would aggregate it as [bed2db and visualize it as 2D rectangles](https://docs.higlass.io/track_types.html#d-rectangle-domain) on top of the actual HiChIP contact frequency map, so you can assess the performance of the peak caller. 

To load the contact map, the hichipper docs say that it runs the HiCPro pipeline, so you should be able to ingest the HiCPro output with `cooler load`, or use [this script from HiCPro](https://github.com/nservant/HiC-Pro/blob/master/bin/utils/hicpro2higlass.sh).

**Comment by docdot** [comment]
Thanks for your reply.
I didn't make clear before, but what I want is to do a pileup of the Hi-ChIP (hichipper output) using this tool https://github.com/Phlya/coolpuppy
The idea is to have something similar a 1D ChIP-seq metaplot (but 2D one in this case)
I will try this cooler cload pairs option you pointed then.
Thanks

**Comment by nvictus** [comment]
OK, sounds good!

Btw, for whatever 2D regions you will be aggregating, it might be informative to also do it on the unfiltered HiChIP contact map. In the ChIP-seq analogy, you'd typically make metaplots from coverage tracks (bigwigs/bams) rather than from peak call intervals (bed).

**Comment by Phlya** [comment]
Hi, developer of coolpuppy here :)

Unless I am misunderstanding something, I agree with Nezar there - use the bedpe files with loop annotation that you have and create coolers for all HiChIP contacts, which should be very easy with `cooler cload pairs`.

**Comment by nvictus** [comment]
Going to close this as resolved. If you still have questions or are running into problems, feel free to re-open.
