### ISSUE TITLE
No error when --balance-args are incorrect

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#185]
I accidentally did `cooler zoomify blabla --balance-args "---cis-only"` - and there was no error or feedback at all, but it just didn't do balancing, which is confusing. Perhaps it should fail from the beginning or give a warning or something?

Related to the aftermath of such errors - perhaps `cooler balance` should be able to deal with multi-resolution files and just apply the same command to all zoom levels? Would save people from trouble writing a script that iterates over all zoom levels and runs `balance`.

**Comment by nvictus** [comment]
This is fixed in #204
