### ISSUE TITLE
make pysam an optional dependency

### ISSUE THREAD

**Issue by cmdoret** [mirnylab/cooler#187]
Hello, 

Pysam can be quite a pain to install on certain HPC and is not available on all platforms.
I noticed pysam is only used to read tabix files, yet it is a mandatory dependency.

Pysam is only required at the line below and an informative message is given if it is not present.

https://github.com/mirnylab/cooler/blob/843dadca5ef58e3b794dbaf23430082c9a634532/cooler/create/_ingest.py#L637-L640

For people developing libraries that just need to interact with cool files through the cooler API, having pysam as a dependency is a lot of overhead. Would it not make sense to make pysam an optional dependency ?

**Comment by nvictus** [comment]
Agreed! Let's make it optional. 

Regardless, if you're having trouble on a particular HPC, are you able to use conda there? I've had good success with installing pysam with bioconda.

**Comment by cmdoret** [comment]
Yes, I solved the problem via conda but some people would rather not use it (e.g. because it's slow), and for (the minority of) windows users, pysam is simply not available.

Thank you ! :)
