### ISSUE TITLE
how to load custom balance weight value?

### ISSUE THREAD

**Issue by yuxuth** [mirnylab/cooler#200]
Hi, 
I'm working on Hichip datasets, which need a different balance strategy to normalize the chip efficiency. 
Is there any way I can add a pre-calculated custom weight value for each bin in my cooler file?  I noticed when using hic2tools, multiple normalization weights are appended to cooler bin column.  Would you please advise how to add a custom weight value to cooler, similar as what hic2tools did?

Thank you!

**Comment by nvictus** [comment]
Hi!

Does the following workflow make sense?

```python
# Calculate your weight column, making sure it is aligned with the bin table.
bins = clr.bins()[:]
bins['my_weight'] = compute_my_weights(bins, ...)

# Insert into the HDF5 file by accessing the underlying h5py handle.
# Compression is optional.
with clr.open('r+') as f:
    f['bins'].create_dataset(
        'my_weight', 
        data=bins['my_weight'].values, 
        compression='gzip', 
        compression_opts=6
    )

# Assuming the normalization is multiplicative, cooler can apply the 
# balancing automatically if you pass the name of the weight column
selector = clr.matrix(balance='my_weight')
result = selector.fetch('chr10:10M-20M')
```

**Comment by yuxuth** [comment]
Great! Thank you so much for the prompt reply. I really appreciate your help! 

Best, Yu
