### ISSUE TITLE
Issue with 'sparse'

### ISSUE THREAD

**Issue by aggmanu** [mirnylab/cooler#207]
Hi,

I seem to be having a weird issue with the 'sparse' setting. I am analyzing 4DNFIFLDVASC.mcool. Below are the commands:

Commands:
filepath = '4DNFIFLDVASC.mcool::resolutions/100000'
arr = c.matrix(balance=False, sparse = True)[22844:22848, 22844:22848]
print(arr)

Output:
 (0, 0)	30069
  (0, 1)	9965
  (0, 2)	4088
  (0, 3)	2283
  **(1, 1)	17379**
  (1, 2)	2910
  (1, 3)	1422
  **(1, 1)	13121**
  (1, 2)	5998
  (1, 3)	2078
  (2, 2)	32768
  (2, 3)	7086
  (3, 3)	26739
  (1, 0)	9965
  (2, 0)	4088
  (3, 0)	2283
  (2, 1)	2910
  **(3, 1)	1422**
  (2, 1)	5998
  **(3, 1)	2078**
  (3, 2)	7086

 Also notice that the number of entries is greater than 16. Please let me know if I am doing something wrong here.

Thanks,
Manu

**Comment by nvictus** [comment]
You're right. Some pixels are "split" across multiple records. This could happen in some places during zoomification in older versions of cooler. You get the correct values by summing the duplicate entries: `arr.sum_duplicates()`. Converting to dense `arr.toarray()` also does this automatically.

You can also re-zoomify the file from the base resolution to eliminate it entirely:

```sh
cooler zoomify --balance 4DNFIFLDVASC.mcool::resolutions/1000 -o 4DNFIFLDVASC.new.mcool
```

**Comment by aggmanu** [comment]
Thank you very much for the quick help and detailed instructions!
