### ISSUE TITLE
cooler balance column visibility

### ISSUE THREAD

**Issue by brainfo** [mirnylab/cooler#214]
I have a cool file like this (publicly availabel raw data from paper NCBI (Nora EP et al. (2017) PMID:28525758) )  :
`{
    "bin-size": 40000,
    "bin-type": "fixed",
    "creation-date": "2020-07-22T22:14:37.146085",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 3,
    "generated-by": "HiCMatrix-13",
    "generated-by-cooler-lib": "cooler-0.8.6.post0",
    "genome-assembly": "unknown",
    "nbins": 68149,
    "nchroms": 22,
    "nnz": 116484869,
    "storage-mode": "symmetric-upper",
    "sum": 237680042.0,
    "tool-url": "https://github.com/deeptools/HiCMatrix"
}`
after cooler balance with default parameters, it seems that the matrix values are low (40kb bin):
![image](https://user-images.githubusercontent.com/11832080/89146492-7b593800-d586-11ea-9009-da902086b42c.png)
Is this kind of pattern normal?
Thanks!

**Comment by nvictus** [comment]
Hello! It looks like you created this file yourself on 2020-07-22 with HiCExplorer. Could you show the code you used to create that plot? One possibility is that the balancing weights are flipped. @joachimwolff might have some insight here.

**Comment by joachimwolff** [comment]
Can you post me the commands you used?

**Comment by brainfo** [comment]
Thank you for your help!
The problem is that I haven't update pygenometracks and hicexplorer to the stable/latest version.
Now I have got it right (similar visual effect as shown on 4DN).
The result of cooler balance is a doubly stochastic matrix so I need to adjust the color mapping values to something like 1e-5, but the scale and proportion of all interaction values seem just fine. So my question solved.
Thank you very much for your suggestions!
