### ISSUE TITLE
cooler/higlass for capture Hi-C data

### ISSUE THREAD

**Issue by nservant** [mirnylab/cooler#216]
Hi guys,

I was trying to analyse capture Hi-C data with cooler/higlass but I'm facing a couple of issues.
Let say I have a Hi-C map on chr1 from range A to B.
I processed the data with HiC-Pro and I have now a sparse text format with bin1/bin2/count and a bin file from A to B.

`cooler load -f coo --one-based CAPTURE.bed CAPTURE.mat CAPTURE.cool`

works well.
However, when I try to zoomify with

`cooler zoomify --balance CAPTURE.cool -r 5000,10000,20000,40000`

It crashes with 
`cooler.create._ingest.BadInputError: Found a bin ID that exceeds the declared number of bins. Check whether your bin table is correct.`

I guess this is because when I zoomify, I'm going outside the range of my A-B capture.

Note that if I'm doing the same with the whole chromosome size, it works.
However, as soon as I normalize, the `higlass` output is empty, I have no map.
So in theory, I would like to run the normalization of my capture region only, and the fact that I have the whole chromosome may explain why there is nothing in higlass.

Therefore, I normalized the data by myself and try to build a cooler file but I have
`TypeError: Cannot cast array from dtype('float64') to dtype('int32') according to the rule 'safe'`
But I though that this issue of floating value was already fixed ?

Any idea is welcome.
Best
Nicolas

**Comment by nservant** [comment]
update. 
I manage to transform iced normalized data with the `--count-as-float` option but still nothing in higlass

**Comment by Phlya** [comment]
Hi Nicolas,

If your data of the kind where you enrich for a particular extended region? I've worked with C-TALE data which is the same approach, and I mapped all data to the whole genome and loaded it all into a cooler (I basically used the normal distiller pipeline without balancing), then normalized using https://github.com/ArtemLuzhin/C-TALE-Normalization

Then you avoid zoomifying small regions, while you can also apply balancing to your data.

**Comment by nservant** [comment]
Thanks @Phlya , and then were you able to see your data in Higlass ?
Because now I think I have a mcool file either genome wide or chromosome wide, with my raw or normalized capture data there.
But the Higlass screen is empty.
Thanks

**Comment by Phlya** [comment]
Yes, it worked in HiGlass! That normalization approach stores weights in the normal way as cooler does, it should behave just like a regular cooler file in all ways.

**Comment by nvictus** [comment]
@nservant, could you check what kind of balancing weights got produced? I wonder if they ended up being NaN somehow.

```
cooler dump -t bins CAPTURE.cool::resolutions/40000
```

**Comment by nvictus** [comment]
I just thought of another potential issue: your zoom levels might not be deep enough for HiGlass to render tiles if you are sufficiently zoomed out (if you are only going up to 40kb). You may need to zoom in close enough to start seeing things, or include coarser zoom levels in your mcool -- there is new syntax to make it easier #203.

**Comment by nservant** [comment]
Hi,
Indeed, sorry, it was my fault. I made a mistake in the resolution. It works now !
And your command also works.

```
>>cooler dump -t bins --header CAPTURE.mcool::resolutions/10000 | head
chrom	start	end
chrX	0	10000
chrX	10000	20000
chrX	20000	30000
chrX	30000	40000
chrX	40000	50000
chrX	50000	60000
chrX	60000	70000
chrX	70000	80000
chrX	80000	90000
```

Thanks guys for the quick support. I'm closing the issue.
N

**Comment by nservant** [comment]
Sorry, back to this with a short question.
Now that I do have `cool` file with my own normalized data, is there a way to define a weight object (I guess to 1) ?
Because when I try to run insulation score, it expects a weight object ;

```
cooltools diamond-insulation --window-pixels CAPTURE_iced.cool 20

KeyError: "Unable to open object (object 'weight' doesn't exist)"
```
Thanks

**Comment by nvictus** [comment]
You can do the following:

```
import cooler
import numpy as np

filepath = 'CAPTURE.mcool'

for grouppath in cooler.fileops.list_coolers(filepath):
    clr = cooler.Cooler(f'{filepath}::{grouppath}')
    with clr.open('a') as grp:
        grp['bins'].create_dataset(
            'weight', 
            data=np.ones(grp['bins/chrom'].shape), 
            compression='gzip', 
            compression_opts=6
        )
```

But this should be fixed in cooltools. Could you open an issue there?

**Comment by nservant** [comment]
done https://github.com/mirnylab/cooltools/issues/176
