### ISSUE TITLE
How to extract contact matrix of each chromosome from merged cool file ?

### ISSUE THREAD

**Issue by Paranoid-mike** [mirnylab/cooler#217]
Hi, recently i'm dealing with Hi-C data.But i'm confused about how to extract numpy matrix from an merged multi-resolution .mcool file. And i didn't fiind any clue or guide on documentation or the original paper.
**Here is my code below:**
`c=cooler.Cooler('/data/4DN/4DNFIFLDVASC.mcool::resolutions/50000')

print(c.info)
print(c.chroms()[:])
selector=c.matrix(balance=True, sparse=True)
chrms=['chr1','chr2','chr3','chr4','chr5','chr6','chr7','chr8','chr9','chr10','chr11','chr12','chr13','chr14','chr15','chr16','chr17','chr18','chr19','chr20','chr21','chr22','chrX','chrY']

for i in chrms:
        #arr = mat.toarray(c.matrix(balance=True, sparse=True))
        data=selector.fetch(i,i)
        #arr = data.toarray(data)
        #print(data[:10])
        np.savetxt(i+".txt",data,delimiter="\t",fmt="%s")
`
**And here is the error message below :**
`  File "cooler_extract.py", line 21, in <module>
    np.savetxt(i+".txt",data,delimiter="\t",fmt="%s")
  File "<__array_function__ internals>", line 6, in savetxt
  File "/media/wjn/zzp/peakachu/3dgenome/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1372, in savetxt
    "Expected 1D or 2D array, got %dD array instead" % X.ndim)
ValueError: Expected 1D or 2D array, got 0D array instead
`

**Comment by nvictus** [comment]
Not sure what's going on. Here's my attempt at reproducing using the same file. I never get a 0-D output:

```python
clr = cooler.Cooler('4DNFIFLDVASC.mcool::resolutions/50000')
selector = clr.matrix(balance=True, sparse=True)

for chrm in clr.chromnames:
    data = selector.fetch(chrm)  # same as fetch(chrm, chrm)
    print(chrm, data.shape) 
```

```
chr1 (4980, 4980)
chr2 (4844, 4844)
chr3 (3966, 3966)
chr4 (3805, 3805)
chr5 (3631, 3631)
chr6 (3417, 3417)
chr7 (3187, 3187)
chr8 (2903, 2903)
chr9 (2768, 2768)
chr10 (2676, 2676)
chr11 (2702, 2702)
chr12 (2666, 2666)
chr13 (2288, 2288)
chr14 (2141, 2141)
chr15 (2040, 2040)
chr16 (1807, 1807)
chr17 (1666, 1666)
chr18 (1608, 1608)
chr19 (1173, 1173)
chr20 (1289, 1289)
chr21 (935, 935)
chr22 (1017, 1017)
chrX (3121, 3121)
chrY (1145, 1145)
```

**Comment by nvictus** [comment]
Oh, wait. I see. You want numpy arrays, but you're asking for scipy sparse matrices. `np.savetxt` doesn't know what to do with those.

If you really want dense numpy arrays:

```python
clr = cooler.Cooler('4DNFIFLDVASC.mcool::resolutions/50000')
selector = clr.matrix()  #  same as clr.matrix(balance=True, sparse=False)

for chrm in clr.chromnames:
    data = selector.fetch(chrm)  # same as fetch(chrm, chrm)
    print(chrm, type(data), data.shape) 
    np.save(chrm + '.npy', data)
```

You also can use `np.save`/`np.load`, which is binary instead of text.

If you want to write a sparse representation to a text file, try [cooler dump](https://cooler.readthedocs.io/en/latest/cli.html#cooler-dump) with the `-r` parameter.

**Comment by Paranoid-mike** [comment]
Thanks a lot nvictus!By the way is  `cooler dump` the command line cooler?

**Comment by nvictus** [comment]
Yes, that's right.

**Comment by nvictus** [comment]
Going to close this. Feel free to re-open if this didn't solve your problem.
