### ISSUE TITLE
Efficiently fetch thousands of regions

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#23]
Hi, is there a way to efficiently fetch thousands of regions from a cooler file (or a few files in parallel?)? I am comparing "density" (sum of Hi-C interactions) along the genome across 3 datasets, and want to do it with 25 or 50 kb sliding windows, and it takes a very long time even with 4 processes... Loading a whole chromosome is not an option, since at 5 kb (Hi-C resolution I use) it doesn't fit into memory. Loading chromosomes as big chunks is an option, but complicates things.
Cheers,
Ilya

**Comment by nvictus** [comment]
Closing as these kinds of operations are the purview of cooltools.
