### ISSUE TITLE
Problem using 'balance' with CLI

### ISSUE THREAD

**Issue by carlvitzthum** [mirnylab/cooler#31]
If a 'weight' column already exists in a cool file (i.e. the file has already been balanced), running the balance command causes an error.

Using /tests/data/GM12878-MboI-matrix.2000kb.cool,
`cooler balance -p 10 tests/data/GM12878-MboI-matrix.2000kb.cool`
followed by
`cooler balance -p 10 tests/data/GM12878-MboI-matrix.2000kb.cool --force`
causes the following error:
KeyError: "Couldn't delete link (No write intent on file)". 

Ran across this testing CLI tools on a .cool file created by a .hic to .cool converter I wrote and thought you all should know.

**Comment by nvictus** [comment]
Thanks, Carl! I can't reproduce the error on your example, though. Which version are you using?

**Comment by carlvitzthum** [comment]
Hi Nezar, I'm using cooler 0.5.3 and h5py 2.6.0.

**Comment by nvictus** [comment]
Ah yes, that's patched in 0.6.1.
