### ISSUE TITLE
Best way to convert other formats to cooler

### ISSUE THREAD

**Issue by ursinedeity** [mirnylab/cooler#33]
Hi, I have several matrices stored in various format like hic format, and output from mirnylib *.hm, and plain text matrix. What's the best way to convert these matrices to cooler? I can easily read these matrices into memory but it seems that the cooler.io.create() is not functioning now. 

One other issue is that these matrices may already be balanced. Can the cooler store counts other than int32, like float32?

**Comment by Phlya** [comment]
If you have a fragment dataset from hiclib, cooler can read it directly to make a cooler file.

**Comment by ursinedeity** [comment]
Thanks, but what if I don't have hdf5 fragment dataset? Some dataset we only have *.hm file available.

**Comment by nvictus** [comment]
Hi Nan,

For hic files, you can use @carlvitzthum's [hic2cool](https://github.com/4dn-dcic/hic2cool).

The `cooler.io.create` should be functioning, but the API has [changed](http://cooler.readthedocs.io/en/latest/api.html#cooler.io.create) from what is shown in the tutorial. For now, if you have a whole genome `.hm` file that fits in memory, you can load that as a numpy array and use the `cooler.io.DenseLoader` to load it into a cooler. Make sure you know the exact set of chromosomes, their order and the resolution.

Here's an example using test data in the repo:

```python

binsize = 2000000
chromsizes = pandas.read_csv(                                                            
    'tests/data/hg19-chromsizes.select.txt', 
    sep='\t', 
    names=['name', 'length']).set_index('name')['chr1':'chrX']['length']   # only contains chr1-22+X
bins = cooler.binnify(chromsizes, binsize)
heatmap = np.load('tests/data/IMR90-MboI-matrix.2000kb.npy')

iterator = cooler.io.DenseLoader(heatmap)
cooler.io.create('/tmp/output.2000kb.cool', chromsizes, bins, iterator, assembly='hg19')
```

Currently, `cooler.io.create` coerces the `count` column to integer dtype, as it is intended to hold the raw counts (with optional additional columns storing transformed data, but this currently has to be done manually). If you have only corrected data and have lost the original raw counts, you can hack `cooler` to store counts as floats by monkey patching the constant `cooler._writer.COUNT_DTYPE = np.float32` or `np.float64` before following the above recipe.

If you have our old `byChr` files, there is no direct way to convert them yet. If they aren't too large, you could concatenate them into one numpy array and use the method above. We can also add a new matrix loader for that file type if necessary.

**Comment by ursinedeity** [comment]
Thanks Nezar! Very informative.
