### ISSUE TITLE
Get complete matrix from cooler dump?

### ISSUE THREAD

**Issue by cmdcolin** [mirnylab/cooler#41]
I was curious if the output of cooler dump/show can get a text version of the contact matrix? Outputting a  triangular matrix as a text file would be cool :)

**Comment by nvictus** [comment]
Cooler dump can dump a sparse triplet or bedGraph like output.

Did you mean something more like a dense ASCII pretty printer? It does not provide that.

If your matrix isn't very large, the easiest way to do that would be 

```
>>> np.savetxt(file, array, fmt='%g', delimiter='\t')
```
though you may want to play with the float format and other options.

Pandas has some more formatting flexibility and will leave NaNs blank by default.
```
>>> a = np.array([[1,np.nan,3],[4,5,6]])
>>> print(pd.DataFrame(a).to_csv(header=False, index=False, sep='\t'))
1.0		3.0
4.0	5.0	6.0

```
If this is something you'd really find useful for displaying small selections, it might be possible to include it as an option to cooler dump, but I'd like to see the formatting options prototyped first.

**Comment by cmdcolin** [comment]
I guess my thought was to get the output as similar to what could just be fed into a naive heatmap function or triangular plot! Does that already exist in some other form?

**Comment by nvictus** [comment]
Not entirely sure I understand what kind of output you're looking for, but perhaps this is it or something close?

https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/dump_cworld.py

It's part of our cooltools package, which isn't following a stable development cycle as of yet. It dumps the text to the Dekker lab "C-World" text format. Hope that helps!

**Comment by cmdcolin** [comment]
I guess perhaps I didn't see that there are already things like heatmap in the readme so maybe I can look into how that works, but I guess I just wanted like a "text output" of the heatmap data

in any case maybe close :)
