### ISSUE TITLE
Long chromosome names cause silent problems in coarsegrain

### ISSUE THREAD

**Issue by pkerpedjiev** [mirnylab/cooler#44]
Having  chromosome names which are longer than 32 characters leads to hard to detect problems in downstream analysis. When running `cooler coarsegrain`, the chromosome names that are obtained from the bins (via the `special_dtype`) don't match those in the `chroms` table, leading to incorrect bin_offsets and no coarse-graining.

The root cause appears to be the fact that chromosome names are truncated to 32 characters in `_writer.py` (e.g. `CHROM_DTYPE = np.dtype('S32')`), whereas they're kept in their original form in `write_bins` (e.g. `enum_dtype = ...`).

I've submitted a [PR](https://github.com/mirnylab/cooler/pull/45/) which errors out of the `cload` program when the chromosome names (sequence ids) are longer than 32 characters. Ideally this limit should be increased to 64 or 128 bytes as longer sequence ids are not uncommon, but I'm not sure if this will break backward compatibility with existing cooler files. In either case, there should be at least a warning or even an error because this will lead to downstream issues (as in `coarsegrain`) which are difficult to diagnose.

**Comment by nvictus** [comment]
Thanks! This is a good fix for now. It will probably be better to make the chromosome names enums as they are in the bin table. There is a chance this can be done seamlessly with few backwards compatibility issues. I'll start a new issue.

**Comment by nvictus** [comment]
See #46
