### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by ya-guo** [mirnylab/cooler#48]
Could you explain what's the difference between a.k.a balancing and ICE(iterative correction and eigenvector decomposition), how to understand balancing, and whether the balancing used in the cooler is a upstate for Hi-C normalisation.

**Comment by nvictus** [comment]
Matrix balancing is the name for the decomposition of a square matrix into a stochastic matrix (flat and equal row and column sums) and a set of balancing weights. The IC part of ICE is an algorithm for matrix balancing on a symmetric matrix like a Hi-C contact matrix. Algorithms for matrix balancing have been rediscovered several times in different fields for different purposes (e.g. in statistical modeling and numerical linear algebra). Lior Pachter even wrote an interesting [blog post](https://liorpachter.wordpress.com/2013/11/17/imakaev_explained/) about it.

The balancing algorithm implemented in cooler is a sparse, parallel and out-of-core (i.e. works in chunks that fit in memory) version of the iterative correction method in [Imakaev et al](http://www.nature.com/nmeth/journal/v9/n10/abs/nmeth.2148.html). One trivial difference is that the output balancing weights in cooler are multiplicative (thus, 1/bias as defined in the original paper). Implementing a sparse and out-of-core method was necessary for scaling up to very large high-resolution Hi-C data.

**Comment by brainfo** [comment]
> Matrix balancing is the name for the decomposition of a square matrix into a stochastic matrix (flat and equal row and column sums) and a set of balancing weights. The IC part of ICE is an algorithm for matrix balancing on a symmetric matrix like a Hi-C contact matrix. Algorithms for matrix balancing have been rediscovered several times in different fields for different purposes (e.g. in statistical modeling and numerical linear algebra). Lior Pachter even wrote an interesting [blog post](https://liorpachter.wordpress.com/2013/11/17/imakaev_explained/) about it.
> 
> The balancing algorithm implemented in cooler is a sparse, parallel and out-of-core (i.e. works in chunks that fit in memory) version of the iterative correction method in [Imakaev et al](http://www.nature.com/nmeth/journal/v9/n10/abs/nmeth.2148.html). One trivial difference is that the output balancing weights in cooler are multiplicative (thus, 1/bias as defined in the original paper). Implementing a sparse and out-of-core method was necessary for scaling up to very large high-resolution Hi-C data.

Would you suggest a "Threshold value of variance of the marginals for the algorithm to converge" to use? the default is e-5, is this the value that suits most cases or it would depend on some features of the matrix?
Thank you very much!

**Comment by rysterzhu** [comment]
Do we need to correct the sequencing depth of the data by downsample or scale before doing the balance?
Thanks
