### ISSUE TITLE
cli does not print usage of specific commands

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/cooler#49]
"cooler dump" and other commands without arguments could print the page of the manual that describes the usage. It would make CLI much easier.

**Comment by nvictus** [comment]
`cooler dump -h` or `cooler dump --help` does what you want.

No args gives you plain usage without help text, which is standard. But it should say something like `use -h option for help`, which it currently doesn't.

**Comment by nvictus** [comment]
Click doesn't make this easy to do for individual subcommands, but I was able to put a general disclaimer when one types the root `cooler` command.

```
Usage: cooler [OPTIONS] COMMAND [ARGS]...

  Type -h or --help after any subcommand for more information.

Options:
  --debug / --no-debug  Verbose logging
  -pm, --post-mortem    Post mortem debugging
  --version             Show the version and exit.
  -h, --help            Show this message and exit.

Commands:
...
```
