### ISSUE TITLE
bioconda installation on python 3.6 fails 

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/cooler#53]
UnsatisfiableError: The following specifications were found to be in conflict:
  - cooler -> multiprocess -> python 2.7* -> openssl 1.0.1*
  - python 3.6*

**Comment by nvictus** [comment]
Bioconda doesn't yet provide 3.6 builds. Hopefully this will be added soon. See https://github.com/bioconda/bioconda-recipes/pull/3338. Using 3.6 will require pip install for now.

**Comment by nvictus** [comment]
bioconda has upgraded to support for 2.7, 3.5, 3.6, so it should work now.
