### ISSUE TITLE
Crash with large datasets

### ISSUE THREAD

**Issue by ezorita** [mirnylab/cooler#54]
It seems that large datasets overflow the size flag used by "Pool". I ran cooler cload succesfully with small datasets but with several billion contacts:

`cooler cload tabix binfiles/bin_1kb.bed dataset.scf.bgz dataset.cool`

This is 1kb binning, with > 1billion contacts in dataset.scf I get the following error:
```
INFO:cooler:Using 8 cores
/usr/local/lib/python2.7/dist-packages/cooler/_reader.py:232: UserWarning: NOTE: When using the Tabix aggregator, make sure the order of chromosomes in the provided chromsizes agrees with the chromosome ordering of read ends in the contact list file.
  "NOTE: When using the Tabix aggregator, make sure the order of "
INFO:cooler:Creating cooler at "/scratch/dataset.cool::/"
INFO:cooler:Writing chroms
INFO:cooler:Writing bins
INFO:cooler:Writing pixels
INFO:cooler:chrM
INFO:cooler:chrY
INFO:cooler:chr21
INFO:cooler:chr22
INFO:cooler:chrX
INFO:cooler:chr19
INFO:cooler:chr20
INFO:cooler:chr18
INFO:cooler:chr9
INFO:cooler:chr17
INFO:cooler:chr16
INFO:cooler:chr15
INFO:cooler:chr13
INFO:cooler:chr14
INFO:cooler:chr8
INFO:cooler:chr7
INFO:cooler:chr6
INFO:cooler:chr5
INFO:cooler:chr12
INFO:cooler:chr4
INFO:cooler:chr11
Traceback (most recent call last):
  File "/usr/local/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cooler/cli/cload.py", line 186, in tabix
    create(cool_path, chromsizes, bins, iterator, metadata, assembly)
  File "/usr/local/lib/python2.7/dist-packages/cooler/io.py", line 164, in create
    filepath, target, n_bins, iterator, h5opts, lock)
  File "/usr/local/lib/python2.7/dist-packages/cooler/_writer.py", line 174, in write_pixels
    for chunk in iterator:
  File "/usr/local/lib/python2.7/dist-packages/cooler/_reader.py", line 313, in __iter__
    for df in self._map(self.aggregate, chroms):
  File "/usr/local/lib/python2.7/dist-packages/multiprocess/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/lib/python2.7/dist-packages/multiprocess/pool.py", line 567, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '[     bin1_id  bin2_id  count
0     384852  1127363      1
0     384858   977744      1
2     384858  1890814      1
1     384858  1977029      1
2     384862  1685662      1
1     384862  2310165      2
3     384862  2603767      1
0     384862  2892389      1
0     384876  2196724      1
0     384887  1889333      1
1     384889  1079339      1
0     384889  2820833      1
0     384890  2308658      1
0     384894  1879589      1
0     384896  2261960      1
20    384899   417637      1
27    384899   528891      1
24    384899   943862      1
3     384899  1228810      1
5     384899  1241744      1
28    384899  1297021      1
26    384899  1485562      1
1     384899  1530749      1
22    384899  1530863      2
2     384899  1531657      1
4     384899  1539596      1
21    384899  1551590      1
6     384899  1662865      1
18    384899  1664090      1
10    384899  1668517      1
..       ...      ...    ...
43    519732  2160311      1
57    519732  2175747      1
74    519732  2186566      1
107   519732  2199037      1
26    519732  2217834      1
64    519732  2220820      1
82    519732  2254178      1
83    519732  2261352      1
44    519732  2272952      1
2     519732  2302728      1
23    519732  2356330      1
0     519732  2373634      1
106   519732  2396659      1
69    519732  2418477      1
6     519732  2435624      1
59    519732  2435848      1
50    519732  2518239      1
98    519732  2550221      1
38    519732  2558119      1
21    519732  2559581      1
66    519732  2596125      1
70    519732  2616625      1
24    519732  2626677      1
37    519732  2724006      1
101   519732  2737631      1
41    519732  2772148      1
13    519732  2838601      1
11    519732  2862142      1
71    519732  2868541      2
72    519732  2922302      1

[68481974 rows x 3 columns]]'. Reason: 'IOError('bad message length',)'
```

Probably an overflow on the size flag of Pool... ?

**Comment by nvictus** [comment]
This seems to be due to a limit on the size of the data chunks that workers can send between processes. See https://bugs.python.org/issue17560.

The solution is a finer division of the data for binning, which is issue #52 . Now that it's clearly causing binning to fail in some cases, I'll make it high priority.

**Comment by nvictus** [comment]
Out of curiosity, are you on Python 2.7? Based on the Python bug report, the serialization limit may be resolved in later versions.

**Comment by ezorita** [comment]
Yes, the previous was on latest pip version of cooler on Python 2.7. I tried the same on python3 but it crashes at the same point. So the serialization limit is not 64-bit in pyhon3 yet...

```
	INFO:cooler:chr1
Traceback (most recent call last):
  File "/usr/local/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cooler/cli/cload.py", line 186, in tabix
    create(cool_path, bins, iterator, metadata, assembly)
  File "/usr/local/lib/python3.4/dist-packages/cooler/io.py", line 239, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/usr/local/lib/python3.4/dist-packages/cooler/_writer.py", line 184, in write_pixels
    for i, chunk in enumerate(iterable):
  File "/usr/local/lib/python3.4/dist-packages/cooler/_binning.py", line 300, in __iter__
    for df in self._map(self.aggregate, chroms):
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 698, in next
    raise value
multiprocess.pool.MaybeEncodingError: Error sending result: '    bin1_id  bin2_id  count
59       10      997      1
48       10    66764      1
41       10   172994      1
13       10   197526      1
34       10   242663      2
71       10   293162      1
73       10   364415      1
30       10   380977      1
44       10   382241      1
58       10   385218      1
37       10   451005      2
49       10   519887     17
50       10   519888      1
25       10   521770      1
27       10   539953      1
43       10   615286      1
11       10   638099      2
32       10   834741      1
35       10   932664      1
42       10   982339      1
47       10  1034359      1
10       10  1038736      1
16       10  1066653      1
7        10  1068812      1
0        10  1069725      1
72       10  1103486      1
51       10  1108710      1
2        10  1114242      1
8        10  1149890      1
22       10  1150246      1
..      ...      ...    ...
3    249239  1124361      1
1    249239  1149569      1
23   249239  1149622      1
12   249239  1456611      1
16   249239  1567474      1
29   249239  1637884      1
14   249239  1641577      1
2    249239  1641732      1
11   249239  1727643      1
13   249239  1848102      1
24   249239  1916536      1
4    249239  1998030      1
0    249239  2055232      1
10   249239  2075324      1
8    249239  2080216      1
7    249239  2101076      1
9    249239  2240580      1
27   249239  2245179      1
6    249239  2338578      1
18   249239  2441007      2
15   249239  2450474      1
30   249239  2480895      1
25   249239  2619897      1
26   249239  2720058      1
21   249239  2874930      1
0    249240   547624      1
2    249240  1287350      1
4    249240  2692791      1
3    249240  2700118      1
1    249240  2880092      1

[124803608 rows x 3 columns]'. Reason: 'error("'i' format requires -2147483648 <= number <= 2147483647",)'
```

**Comment by nvictus** [comment]
Could you try the latest update on develop and see if it solves the problem? All the billion+ pairs files we have are currently in HDF5, so I can't test right away. There is a new parameter `--splitmax` that will divide each chromosome into at most that many chunks. If you can, try setting it somewhere in the range ~5-10.

**Comment by nvictus** [comment]
Well, if multiprocessing queues really do use a signed int32 to measure object size in bytes as the thread says, that limits the chunks sent back from workers to 2GB. Good to know...

**Comment by nvictus** [comment]
Well, turns out pickle [protocol 4](https://www.python.org/dev/peps/pep-3154/#bit-opcodes-for-large-objects) is 64-bit ready, but multiprocessing uses a lower protocol version and it isn't straightforward to override. However, cooler actually uses a replacement package called [multiprocess](https://github.com/uqfoundation/multiprocess) which uses the alternative pickler [dill](https://github.com/uqfoundation/dill), whose protocol version can be overriden!

```
import dill, pickle
dill.settings['protocol'] = pickle.HIGHEST_PROTOCOL
```

That might be the way to go to... Yet, still a good idea to control the chunk sizes ;)

**Comment by nvictus** [comment]
Also worth mentioning that instead of pooling all runs and libraries into one giant pairs file and loading it, you can also load individual libraries into coolers and then merge them together with the new `cooler merge` command.

**Comment by ezorita** [comment]
Yes, it seems to be working fine now. At least the cload process exits without errors and the output files seem to be consistent -- I've tried to read a few small chunks of data from the Python API.

**Comment by ezorita** [comment]
> That might be the way to go to... Yet, still a good idea to control the chunk sizes ;)

Indeed, especially to balance the thread loading. If you expect your multithreading jobs to be very unbalanced, like in a size(chr1)/size(chr21) ~ 5 ratio, as a rule of thumb I'd make at least 5 time more jobs than concurrent threads with a fair scheduler.

**Comment by nvictus** [comment]
I threw in the protocol change too. Feel free to reopen if this issue resurfaces.

**Comment by zhanyinx** [comment]
Hi, 
I had the same problem. Probably I misunderstood your solution because I did not manage to solve the overflow problem. 

**cooler, version 0.7.6**
**Python 2.7.12**

I am analysing the Hi-C from Bonev et al (mm9 build)

I start with a list of contact maps:
-split in chunks the list of contacts
-I generage a .cool file for each of the chunk
-I merge the chunks using cooler merge

The last command gave me the following error:



INFO:cooler:Merging:
PREFIX00.cool
PREFIX01.cool
PREFIX02.cool
PREFIX03.cool
PREFIX04.cool
PREFIX05.cool
PREFIX06.cool
PREFIX07.cool
PREFIX08.cool
PREFIX09.cool
PREFIX10.cool
PREFIX11.cool
Traceback (most recent call last):
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/bin/cooler", line 11, in <module>
    sys.exit(cli())
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/cooler/cli/merge.py", line 43, in merge
    bins = clrs[0].bins()[['chrom', 'start', 'end']][:]
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/cooler/api.py", line 227, in bins
    return RangeSelector1D(None, _slice, _fetch, self._info['nbins'])
KeyError: 'nbins' 



Could you tell me where I did wrong?
Thanks
Zhan
