### ISSUE TITLE
Add more formatting options to cooler dump

### ISSUE THREAD

**Issue by nvictus** [mirnylab/cooler#60]
- [x] Choose column subset
- [x] NaN print format
- [x] symmetrize (#105)

**Comment by nvictus** [comment]
All done. `-m/--matrix` option provides full symmetric output.

**Comment by frankyan** [comment]
Can `cooler dump` dump the non-symmetric matrix? Are any special options needed? Thanks.

**Comment by nvictus** [comment]
A non-symmetric matrix shouldn't require any special options. Report back if it doesn't work.
