### ISSUE TITLE
ability to filter pairs at the aggregation step

### ISSUE THREAD

**Issue by golobor** [mirnylab/cooler#65]
it's not uncommon to aggregate only certain subsets of pairs. The current solution would be to create a separate .pairs file with the subset, index it and then aggregate. This leads to data pollution, and is expensive both to generate and store. The alternative is to filter out pairs dynamically, at the stage of aggregation.

**Comment by nvictus** [comment]
The solution is to use streaming input to `cload pairs` and apply any filters you desire.
