### ISSUE TITLE
Migrating from prior cooler files to current release - commit 459a9ce

### ISSUE THREAD

**Issue by koustav-pal** [mirnylab/cooler#72]
Hi, 

I have cooler files which were generated using packages and manual scripts provided last year between Jan 2016 - Apr 2016. 
Right now I am migrating to the newer release of cooler. While balancing.iterative_correction works fine. Exporting of the files do not. From the error below I am guessing this is related to a mismatch between table headers in the chrom table files attached to the .cool formatted files back then 

```
  File "/home/kpal/BitBucket_Repositories/hiclib_Processing_Pipeline/hiclib-processing/Python_Wrappers/NormalizeCooler.py", line 79, in <module>
    CoolerObject = CoolerHandler.Cooler(IntermediateFilePath)
  File "/lustre/home/kpal/.local/lib/python2.7/site-packages/cooler-0.7.5-py2.7.egg/cooler/api.py", line 78, in __init__
    _ct = chroms(grp)
  File "/lustre/home/kpal/.local/lib/python2.7/site-packages/cooler-0.7.5-py2.7.egg/cooler/api.py", line 366, in chroms
    .append(pandas.Index(h5['chroms'].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "/home/kpal/anaconda2/lib/python2.7/site-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (-------src-dir-------/h5py/h5o.c:3551)
KeyError: "Unable to open object (Object 'chroms' doesn't exist)"
```

Previously, we exchanged some emails with reference to a workaround script for converting fragmentHiC generated objects to .cool formatted objects. I am attaching the script here.
[MakeCoolerObjectFromHDF.txt](https://github.com/mirnylab/cooler/files/1190548/MakeCoolerObjectFromHDF.txt)

The first of my questions are, 

1. I remember reading somewhere in either the cooler page or the hiclib page that conversion from fragmentHiC objects to .cool objects is now natively supported. Even with my PhD hanging on the line I am unable to find it, is it a figment of my imagination or is it supported? 

In this case, I would go through with updating HiCLib and incorporating native conversion within my pipeline. 

2. Would reconverting the .cool files solve all my problems? I took a look at the more updated io.py and it seems the format has gone through some significant changes since last year. Would readapting the conversion script for the new format be a larger task than solving dependencies and bugs that will inevitably rise from point 1? 

This is the format of my .cool files:
```

        group         name       otype  dclass      dim
0           /         bins   H5I_GROUP
1       /bins     chrom_id H5I_DATASET INTEGER     4763
2       /bins          end H5I_DATASET INTEGER     4763
3       /bins        start H5I_DATASET INTEGER     4763
4           /      indexes   H5I_GROUP
5    /indexes  bin1_offset H5I_DATASET INTEGER     4764
6    /indexes chrom_offset H5I_DATASET INTEGER        6
7           /       matrix   H5I_GROUP
8     /matrix      bin1_id H5I_DATASET INTEGER 10473200
9     /matrix      bin2_id H5I_DATASET INTEGER 10473200
10    /matrix        count H5I_DATASET INTEGER 10473200
11          /    scaffolds   H5I_GROUP
12 /scaffolds       length H5I_DATASET INTEGER        5
13 /scaffolds         name H5I_DATASET  STRING        5
```

**Comment by Phlya** [comment]
1. http://cooler.readthedocs.io/en/latest/cli.html#cooler-cload `cooler cload hiclib` is what you want to load `hiclib` fragment data, and you don't have to update `hiclib` for this to work (and I think there is a method in `hiclib` to create `cooler` files now too).

**Comment by nvictus** [comment]
Hi Koustav,

> I took a look at the more updated io.py and it seems the format has gone through some significant changes since last year. 

Yes, the schema was still in flux when we exchanged emails back then and has evolved. Though, depending on exactly at what point, the changes might be trival (e.g., renaming `matrix` to `pixels` and `scaffolds` to `chroms`). If that's the case, you could try a simple rename by cloning the groups in the HDF5 file (e.g., `f['pixels'] = f['matrix']`).

However, I would recommend following @Phlya's suggestion (Thanks, Ilya!). You can either use `cooler cload hiclib` on a hiclib .frag file or update to the latest version of hiclib and use the [fragmentHiC.saveCooler](https://bitbucket.org/mirnylab/hiclib/src/69fc98669cf5d08430c2d389506f678eb3f663e1/src/hiclib/fragmentHiC.py?at=default&fileviewer=file-view-default#fragmentHiC.py-979) method. 

> I am unable to find it, is it a figment of my imagination or is it supported?

Hmm, Max likely added it to the hiclib documentation, but it looks like bitbucket has moved or deleted our docs: http://mirnylab.bitbucket.org/hiclib/index.html  Thanks for helping us catch this!

> Even with my PhD hanging on the line 

Yikes, sorry for the delay! (I've got one of those to complete as well). If you need more specific help feel free to shoot me an email again.

**Comment by koustav-pal** [comment]
Hi Nezar, 

Thanks for the reply. No worries, later that same day I found the scripts v0tov1.py and v1tov2.py buried inside scripts. I used those but then I ran into a numpy index error which arose from me trying to use mirnylib.numutils.iterative_correction to correct the heatmaps. Also must be noted that this is a reproducible error starting from numpy 1.11.x.  Although I cannot reference the particular error atm, it had to do with how masks were being created and the presence of NaNs in the array.

The reason I was using this function was because of a bug in the cis_only iterative_correction provided in cooler. For more details, you should be able to dig up the email correspondence with the subject line, "Ever Increasing variance during chromosomewise normalization (cis only)" 

I'll open a new thread if required.

**Comment by nvictus** [comment]
`cooler.matrix(balance=True)` will fill filtered bins with NaN values (though, not the diagonals omitted from correction, beware) because balancing weights of filtered bins are NaN. Replacing the NaNs with zeros should allow `mirnylib.numutils.iterative_correction` to work.

Can you send me an example file where cis-only correction fails?

**Comment by nvictus** [comment]
Closing this. Let's open a new issue if problems with cis-only balancing resurfaces.
