### ISSUE TITLE
Bug using single-column chromosomes file in csort

### ISSUE THREAD

**Issue by nadabrovitxka** [mirnylab/cooler#74]
Hi,
I am processing 12 different datasets but 8 of them gave me problems using cooler zoomify.
All the same issue : 
`  File "/share/apps/cooler/0.7.4/intel/bin/cooler", line 11, in <module>
    load_entry_point('cooler==0.7.4', 'console_scripts', 'cooler')()
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/cooler-0.7.4-py2.7.egg/cooler/cli/aggregate.py", line 234, in zoomify
    n_zooms, zoom_levels = multires_aggregate(cool_uri, outfile, nproc, chunksize, lock=lock)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/cooler-0.7.4-py2.7.egg/cooler/cli/aggregate.py", line 127, in multires_aggregate
    lock
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/cooler-0.7.4-py2.7.egg/cooler/cli/aggregate.py", line 52, in aggregate
    append=True)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/cooler-0.7.4-py2.7.egg/cooler/io.py", line 237, in create
    file_path, target, meta.columns, iterable, h5opts, lock)
  File "/share/apps/cooler/0.7.4/intel/lib/python2.7/site-packages/cooler-0.7.4-py2.7.egg/cooler/_writer.py", line 201, in write_pixels
    dset.resize((nnz + n,))
  File "/share/apps/h5py/2.7.0rc2/intel/lib/python2.7/site-packages/h5py-2.7.0rc2-py2.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 358, in resize
    self.id.set_extent(size)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/wang/h5py-2.7.0rc2/h5py-2.7.0rc2/h5py/_objects.c:2831)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/wang/h5py-2.7.0rc2/h5py-2.7.0rc2/h5py/_objects.c:2789)
  File "h5py/h5d.pyx", line 274, in h5py.h5d.DatasetID.set_extent (/home/wang/h5py-2.7.0rc2/h5py-2.7.0rc2/h5py/h5d.c:4254)
ValueError: Unable to set extend dataset (Dimension cannot exceed the existing maximal size (new: 155060 max: 154290))`

Here cooler info for a file that failed and a file that completed.
`
[rr1859@log-0 Nature_HiC_embryos]$ cooler info GSM2203839_ICM_rep1_allValidPairs.cool
{
    "nchroms": 35, 
    "bin-type": "fixed", 
    "nbins": 68162, 
    "sum": 40798013, 
    "format-url": "https://github.com/mirnylab/cooler", 
    "format-version": 2, 
    "genome-assembly": "unknown", 
    "nnz": 12310943, 
    "generated-by": "cooler-0.7.4", 
    "format": "HDF5::Cooler", 
    "bin-size": 40000, 
    "creation-date": "2017-08-07T18:43:46.662838"
}

[rr1859@log-0 Nature_HiC_embryos]$ cooler info GSM2203840_ICM_rep2_allValidPairs.cool
{
    "nchroms": 35, 
    "bin-type": "fixed", 
    "nbins": 68162, 
    "sum": 62124528, 
    "format-url": "https://github.com/mirnylab/cooler", 
    "format-version": 2, 
    "genome-assembly": "unknown", 
    "nnz": 30163438, 
    "generated-by": "cooler-0.7.4", 
    "format": "HDF5::Cooler", 
    "bin-size": 40000, 
    "creation-date": "2017-08-07T19:00:07.392859"
}`

and the resulting cooler list -l 
`[rr1859@log-0 Nature_HiC_embryos]$ cooler list -l GSM2203839_ICM_rep1_allValidPairs.multi.cool
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/0	20,480,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/1	10,240,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/2	5,120,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/3	2,560,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/4	1,280,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/5	640,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/6	320,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/7	160,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/8	80,000
GSM2203839_ICM_rep1_allValidPairs.multi.cool::/9	40,000

[rr1859@log-0 Nature_HiC_embryos]$ cooler list -l GSM2203840_ICM_rep2_allValidPairs.multi.cool
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/3	2,560,000
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/4	1,280,000
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/5	640,000
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/6	320,000
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/7	160,000
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/8	80,000
GSM2203840_ICM_rep2_allValidPairs.multi.cool::/9	40,000`

Any idea?
Thanks a lot

**Comment by pkerpedjiev** [comment]
Would you able to share one of the files that is causing the error? If privacy is an issue, we could provide you an AWS link to place the file so that it's not visible to the public.

**Comment by nadabrovitxka** [comment]
Files are public.
I uploaded both .cool and .multi.cool files. Rep1 worked, Rep2 fails.
You can find them here:
https://drive.google.com/drive/folders/0B0wnRGWP-yayY0NCTDAxbHRRT28?usp=sharing

**Comment by nadabrovitxka** [comment]
I actually didnt do the mapping myself. Got the list of Valid Pairs from GEO but assumed that their description that it was mapped to mm9 was correct. Then I used  the mm9 chromsizes file I found in your lab's github to build a the bed file with the bins for creating the .cool file. All files were created like this.

**Comment by nvictus** [comment]
The valid pairs files used to create the original cool files wasn't properly sorted, so the cool files you generated weren't upper triangular, giving them more pixels than they should have:

![image](https://user-images.githubusercontent.com/1270651/29091216-37540e7e-7c50-11e7-9f74-a7a2a932da02.png)

Unfortunately, even if you index a pairs file with pairix, it does not ensure the pair records are flipped to reflect the chromosome order (pairix allows you to have records in both blocks (chr1, chr2) and (chr2, chr1)), and in principle it might even "work" even if the file is not block sorted. We should put in some checks to detect this.

1. Could you try resorting the valid pairs files with `cooler csort` and using those to create the cool files?
2. Could you share the valid pairs file you used to create rep1 and rep2?

**Comment by nadabrovitxka** [comment]
I actually couldnt get csort to work when I was processing the files. The .gz and .gz.px2 created this way had only 28 and 78ks even though no error message was printed. I recreated this and upload these files, together with the .pair files I used to generate these to the folder above.
The cool files I sent  before were created using sort -k2,2 -k4,4 -k3,3n -k5,5n and then used pairix to create the index file.
I also put the standard output for the csort I just did.

Thanks so much for the help.

**Comment by nvictus** [comment]
> The cool files I sent before were created using sort -k2,2 -k4,4 -k3,3n -k5,5n and then used pairix

Yup! Sorting without flipping first doesn't resolve the ordering of the left and right alignments in each pair record. You can actually do flipping and sorting in two steps by running `cooler csort --flip-only -c1 2 -p1 3 -c2 4 -p2 5 <pairs.gz> <chromsizes>` and it will print the upper triangular pairs to stdout. Then continue as you did before.

I can't seem to reproduce the empty output on a python 2.7 environment with cooler 0.7.4 and pairix 0.1.6 from bioconda (my guess as to your setup). csort and indexing seem to work using:

```
cooler csort -c1 2 -p1 3 -c2 4 -p2 5 GSM2203839_ICM_rep1_allValidPairs.pairs mm9.chrom.sizes
```
Here's a link to the output [files](https://www.dropbox.com/sh/3wqqsjrtfk16yow/AAAnVP3lnbO2Ah6rt8abt84Ca?dl=0).

Could you describe the environment you're using? Python version, cooler version, pairix version, pypairix version? e.g. a log from "pip list". And the command you invoke.

**Comment by nvictus** [comment]
Actually, can you upload the exact chromsizes file that you used?

**Comment by nadabrovitxka** [comment]
I uploaded the Chrom_sizes_mm9.txt file which was used to generate the mm9_40kb.bed (also uploaded) using cooler makebins. as i said using that bed file i was able to create 4 out of 12 multi.cool files from the same dataset.

The empty output was generated using:
cooler csort  ${sample}.pairs chr_order_mm9.txt -c1 2 -c2 4 -p1 3 -p2 5 -p 10
I also uploaded this chr_order_mm9.txt file
(i just realized this does not have chromosome sizes, it doesnt need them,right?)

pip list
ansible (2.2.1.0)
Babel (0.9.6)
backports.ssl-match-hostname (3.4.0.2)
blivet (0.61.15.59)
Brlapi (0.6.0)
cffi (1.6.0)
chardet (2.2.1)
configobj (4.7.2)
configshell-fb (1.1.18)
coverage (3.6b3)
cryptography (1.3.1)
cupshelpers (1.0)
custodia (0.1.0)
decorator (3.4.0)
di (0.3)
dnspython (1.12.0)
ecdsa (0.13)
empy (3.3.2)
enum34 (1.0.4)
ethtool (0.8)
firstboot (19.5)
fros (1.0)
globus-connect-server (4.0.43)
gssapi (1.2.0)
httplib2 (0.7.7)
idna (2.0)
iniparse (0.4)
initial-setup (0.3.9.36)
iotop (0.6)
ipaclient (4.4.0)
ipaddress (1.0.16)
ipalib (4.4.0)
ipaplatform (4.4.0)
ipapython (4.4.0)
IPy (0.75)
javapackages (1.0.0)
Jinja2 (2.7.2)
jwcrypto (0.2.1)
kerberos (1.1)
kitchen (1.1.1)
kmod (0.1)
langtable (0.0.31)
lxml (3.2.1)
MarkupSafe (0.11)
netaddr (0.7.5)
netifaces (0.10.4)
ntplib (0.3.2)
ofed-le-utils (1.0.3)
paramiko (1.16.1)
perf (0.1)
pip (9.0.1)
ply (3.4)
policycoreutils-default-encoding (0.1)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.63)
pycurl (7.19.0)
pygobject (3.14.0)
pygpgme (0.3)
pyinotify (0.9.4)
pykickstart (1.99.66.10)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
pyparsing (1.5.6)
pyparted (3.9)
pysmbc (1.0.13)
python-augeas (0.5.0)
python-dateutil (1.5)
python-dmidecode (3.10.13)
python-keyczar (0.71rc0)
python-ldap (2.4.15)
python-meh (0.25.2)
python-nss (0.16.0)
python-yubico (1.2.3)
pytz (2012d)
pyudev (0.15)
pyusb (1.0.0b1)
pyxattr (0.5.1)
PyYAML (3.10)
qrcode (5.0.1)
requests (2.6.0)
rtslib-fb (2.1.57)
seobject (0.1)
sepolicy (1.1)
setroubleshoot (1.1)
setuptools (0.9.8)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
SSSDConfig (1.14.0)
targetcli-fb (2.1.fb41)
urlgrabber (3.10)
urllib3 (1.10.2)
urwid (1.1.1)
virtualenv (15.1.0)
wheel (0.29.0)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)
zenmap (6.40)

and anaconda3/4.3.1  cooler/intel/0.7.4  pypairix/intel/0.2.3 pairix 0.2.3

**Comment by nadabrovitxka** [comment]
I think you were right.
I tried the flip command and it was also producing an empty output.
When I used your mm9.chrom.sizes file, it worked.
Is it the naming or it really needs also the chromosome size information?

**Comment by nadabrovitxka** [comment]
OK, 
Starting from the.pairs file I:
1- sorted and indexed using csort and using your chromosome size file (no flipping)
2-created .cool files with cooler and using my mm9_40kb.bed file
3-created .multi.cool with zoomify.

All worked now. I dont get why some files worked with my old chromosome size file while other didnt.

Thanks a lot for the help.

**Comment by nvictus** [comment]
csort should also complain if none of the requested chromosomes are found

**Comment by nadabrovitxka** [comment]
great! 
but did you get why 4/12 samples worked when I did the regular linux sort and then ran cooler cload 
 while the others screwed up?

**Comment by nvictus** [comment]
Oh, they "worked" but created an improperly sorted cooler because many lower triangular pixels exist. They just didn't happen to exceed the maximum number of pixels due to double counting many pixel locations + their transposes.

**Comment by nadabrovitxka** [comment]
makes sense. thanks a lot! hope i wont have to bother you guys much more
