### ISSUE TITLE
Balancing with unequal bins

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooler#80]
Hi, I am curious - what will happen if I have a cooler with unequal bins after IC? Will the balancing make row/column sums equal, or proportional to the bin length? Or is there a way to specify this?

I'm just thinking of making a cooler file with TAD coordinates as bins, and wondering how to deal with balancing it.

Thanks!

**Comment by nvictus** [comment]
Balancing will always balance to equalize coverage of the bins, whatever those bins represent. I think this is actually the desired behavior depending on the research question: e.g. if you bin at the fragment level, you can balance the matrix to determine the relative frequency of contacts captured between those things. 

Balancing in a way that remains proportional to genomic length could be interesting. That amounts to specifying a set of fixed bin-specific weights in addition to the balancing weights being computed and solving:

```
B_ij = a_i*b_i * a_j *b_j * A_ij
```
where 1/a_i is proportional to the genomic bin lengths. Then one solves for the b_i, and the final weights stored will the w_i = a_i * b_i.

P.S. As an aside, are you sure you want to bin by TAD? And if so, which representation makes more sense for the questions you are trying to answer?

**Comment by Phlya** [comment]
Well, if bins are "equal", by length or by number of fragments, then balancing to obtain equal visibility is the only logical way I see. But if the bins are not equal, like in my case, this approach doesn't make sense, since one wouldn't expect equal visibility from them... My other question is actually related to this one, since an easy way to simulate the desired behaviour would be to create a regular equal-bin-size cooler, balance it and then coarsegrain with desired bins.

So... A thought - could I just multiply the weights stored in the cooler in the end by the bin length?

PS
No, I am not sure :) But I thought it could be an easy and fast way to calculate statistics about interactions between different TADs, and wanted to give it a try. I am not sure what you mean in your second question...

**Comment by nvictus** [comment]
> So... A thought - could I just multiply the weights stored in the cooler in the end by the bin length?

Yes, I think you're right. (See edited equation in the first post). If the matrix you actually want is `S_ij * n_i * n_j` and you compute balancing weights `x_i`, according to `A_ij * x_i * x_j = S_ij`, then the true weights you want would be `w_i = x_i * n_i` .

> an easy way to simulate the desired behaviour would be to create a regular equal-bin-size cooler, balance it and then coarsegrain with desired bins.

Agreed. If you coarsegrain the balanced values. Though, I think small discrepancies between this and the previous approach can arise due to ignoring of filtered bins.

> the bins are not equal, like in my case, this approach doesn't make sense, since one wouldn't expect equal visibility from them

I disagree only at a very technical level. Since we're deriving relative contact frequencies between objects, we can in principle choose to make any objects we want to be "equal" and balance accordingly and it wouldn't be "technically wrong" to do so, but the interpretation will change. Maybe it makes sense if you want some kind of length-independent measure of mutual "affinity" between a set of regions, rather than the contact frequencies between them. Though, I can't immediately think of how such a thing could be useful.

**Comment by Phlya** [comment]
Cool, thanks! I guess I'll give it a go and see what happens. This should really simplify and speed up the analysis.
This could also be useful for compartments, I think, by the way.

I agree that technically doing regular balancing with unequal bins is OK, what I mean it doesn't make much sense biologically... At least I also don't see how it can be useful.

**Comment by Phlya** [comment]
OK, so, balancing with unequal bins seems to be broken completely, actually... I created the cooler using `cooler cload hiclib --assembly mm9 $1 $2 $3` (where arguments are the bins file, fragments file and output file). I use cli to balance too - `cooler balance $file`, this is what I get:

```
INFO:cooler:Balancing "serum_tads.cool"
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/tools.py", line 51, in apply_pipeline
    data = func(chunk, data)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/ice.py", line 58, in _marginalize
    np.bincount(pixels['bin1_id'], weights=data, minlength=n)
ValueError: The first argument of bincount must be non-negative
"""
```

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/bin/cooler", line 11, in <module>
    load_entry_point('cooler==0.7.5.dev0', 'console_scripts', 'cooler')()
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/cli/balance.py", line 184, in balance
    map=pool.imap_unordered)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/ice.py", line 257, in iterative_correction
    .reduce(add, np.zeros(n_bins))
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/cooler/tools.py", line 241, in reduce
    return reduce(binop, iter(self.run()), init)
  File "/exports/igmm/eddie/wendy-lab/ilia/Hi-C/lib/python3.5/site-packages/multiprocess/pool.py", line 695, in next
    raise value
ValueError: The first argument of bincount must be non-negative
```
This is the cooler that I got with unequal bins (zipped to allow attachment)
[serum_tads.cool.zip](https://github.com/mirnylab/cooler/files/1306725/serum_tads.cool.zip)

Fetching regions from it is also broken:
`st.matrix(balance=False).fetch('chr1')`
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-43-2e63c99e5e43> in <module>()
----> 1 st.matrix(balance=False).fetch('chr1')

/usr/local/lib/python3.5/dist-packages/cooler/core.py in fetch(self, *args, **kwargs)
    564         if self._fetch is not None:
    565             i0, i1, j0, j1 = self._fetch(*args, **kwargs)
--> 566             return self._slice(self.field, i0, i1, j0, j1)
    567         else:
    568             raise NotImplementedError

/usr/local/lib/python3.5/dist-packages/cooler/api.py in _slice(field, i0, i1, j0, j1)
    294                 grp = h5[self.root]
    295                 return matrix(grp, i0, i1, j0, j1, field, balance, sparse,
--> 296                     as_pixels, join, ignore_index, max_chunk)
    297 
    298         def _fetch(region, region2=None):

/usr/local/lib/python3.5/dist-packages/cooler/api.py in matrix(h5, i0, i1, j0, j1, field, balance, sparse, as_pixels, join, ignore_index, max_chunk)
    597 
    598     else:
--> 599         i, j, v = query_rect(triu_reader.query, i0, i1, j0, j1)
    600         arr = coo_matrix((v, (i-i0, j-j0)), (i1-i0, j1-j0)).toarray()
    601 

/usr/local/lib/python3.5/dist-packages/cooler/core.py in query_rect(triu_reader, i0, i1, j0, j1)
    376     # symmetric query
    377     if (i0, i1) == (j0, j1):
--> 378         i, j, v = triu_reader(i0, i1, i0, i1)
    379         nodiag = i != j
    380         i, j, v = np.r_[i, j[nodiag]], np.r_[j, i[nodiag]], np.r_[v, v[nodiag]]

/usr/local/lib/python3.5/dist-packages/cooler/core.py in query(self, i0, i1, j0, j1)
    268         i, j, v = [], [], []
    269         if (i1 - i0 > 0) or (j1 - j0 > 0):
--> 270             edges = h5['indexes']['bin1_offset'][i0:i1 + 1]
    271             data = h5['pixels'][field]
    272             p0, p1 = edges[0], edges[-1]

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)()

/usr/local/lib/python3.5/dist-packages/h5py/_hl/dataset.py in __getitem__(self, args)
    472 
    473         # Perform the dataspace selection.
--> 474         selection = sel.select(self.shape, args, dsid=self.id)
    475 
    476         if selection.nselect == 0:

/usr/local/lib/python3.5/dist-packages/h5py/_hl/selections.py in select(shape, args, dsid)
     92 
     93     sel = SimpleSelection(shape)
---> 94     sel[args]
     95     return sel
     96 

/usr/local/lib/python3.5/dist-packages/h5py/_hl/selections.py in __getitem__(self, args)
    259             return self
    260 
--> 261         start, count, step, scalar = _handle_simple(self.shape,args)
    262 
    263         self._id.select_hyperslab(start, count, step)

/usr/local/lib/python3.5/dist-packages/h5py/_hl/selections.py in _handle_simple(shape, args)
    445     for arg, length in zip(args, shape):
    446         if isinstance(arg, slice):
--> 447             x,y,z = _translate_slice(arg, length)
    448             s = False
    449         else:

/usr/local/lib/python3.5/dist-packages/h5py/_hl/selections.py in _translate_slice(exp, length)
    486         raise ValueError("Step must be >= 1 (got %d)" % step)
    487     if stop < start:
--> 488         raise ValueError("Reverse-order selections are not allowed")
    489 
    490     count = 1 + (stop - start - 1) // step

ValueError: Reverse-order selections are not allowed
```
(The bins I used are, of course, stored in the cooler)

Is it a bug?..

**Comment by nvictus** [comment]
You somehow ended up with negative pixels. Could you send me the frag file you used?

```
cooler dump -t pixels serum_tads.cool | head
-1	-1	129160
-1	0	18147
-1	1	6913
-1	2	8114
-1	3	2216
-1	4	1674
-1	5	3177
-1	6	1010
-1	7	4076
-1	8	2020
```

**Comment by Phlya** [comment]
It's huge, that won't be easy! But the exact same frag file works fine with with equal 1Mb bins, or any other resolution... I could try again tomorrow with some small frag file and send it if it also doesn't work?

**Comment by nvictus** [comment]
alright, sounds good!

**Comment by Phlya** [comment]
Hi, I shared a link to a file with you by email. I am thinking is it possible this is because the first bin doesn't start at 0, that's why there are negative coordinates? I'll check now.

**Comment by Phlya** [comment]
Yes, this seems to be the problem - after I added another bin there between 0 and the start of the previously first bin balancing works fine. So, I guess, if there are reads that fall before the first bin, there is a problem?

**Comment by nvictus** [comment]
Ah, yes, that is it! So far, the assumption has been that bins are a complete segmentation of each scaffold without gaps. It certainly doesn't have to be this way, but would require updating the aggregators. I can reopen as a new issue. For now, it should at least raise an error.

**Comment by Phlya** [comment]
By they way, when I added a bin in the beginning I only did it for the first chromosome, all others were still not starting from zero (and they are all also not ending at the very last bin) - and it seemed to work!

**Comment by nvictus** [comment]
Continue discussion in #104
