### ISSUE TITLE
Questions related to the Cooler file format

### ISSUE THREAD

**Issue by koustav-pal** [mirnylab/cooler#82]
Hi Nezar, 

Sorry I didn't follow up with the earlier issue regarding the sparse matrices, I planned on following up on it later, but that later never came. Ultimately I migrated back to the last stable build. I'll get to it one of these days!

Currently I am implementing a cooler hdf read function, so I had a few questions regarding the same.

The matrix group has three columns bin1_id, bin2_id and counts. Currently I do not read the bin1_id or bin2_id columns because I assume that all pairs of contacts will be present in a sorted fashion. While preparing the files does the package allow any scenarios where any pairs of contacts may not be present? Such as removing trans interaction counts?  

Because, the hdf read operations are the real bottleneck, I would rather not do an operation if cooler package ensures that all pairs of contacts are provided.

**Comment by nvictus** [comment]
Nonzero pixels are sorted lexicographically by bin1_id and bin2_id. That means **all zero pixels are missing**. See the [data model](http://cooler.readthedocs.io/en/latest/datamodel.html) and [schema](http://cooler.readthedocs.io/en/latest/schema.html). Is this not what you were expecting?

Out of curiosity, is there something the hdf read function handles that the `Cooler.pixels` or `Cooler.matrix` selectors don't? Or is it not in Python?

**Comment by koustav-pal** [comment]
Thanks for the clarification. I was expecting all values for all chromosomes to be present. 

No, the function is not in Python, but in R.

**Comment by nvictus** [comment]
Closing issues labeled "question".
