### ISSUE TITLE
cooler cload pairix on large file halt

### ISSUE THREAD

**Issue by lzlgboy** [mirnylab/cooler#92]
I used to generate cool files from pairs.gz file without problem. 
There is one .pairs.gz which is 10GB, it neneve finish running and just halt there when the output file is
89M .

I am wondering why this file is never finished? Is it too large?

**Comment by nvictus** [comment]
It is likely memory related. Could you try increasing the `--max-split` parameter to 5 or 10 (default is 2)?

**Comment by nvictus** [comment]
This should be handled somewhat automatically now. There is also an index-free version of `cload` in v0.7.8 that lets you control memory usage more directly.
