### ISSUE TITLE
cooler.io.is_cooler python2 and python3

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#94]
Dear cooler-team,

we currently implement a support for your format in our software `HiCExplorer`, see https://github.com/deeptools/HiCExplorer.

I created a cooler file with `cooler.io.create` using Python 2.7 and the check if it is a valid cooler-file `cooler.io.is_cooler` returns `True`. However, if I check the same file with `cooler.io.is_cooler` using Python 3.6 it returns `False`.

Can you tell me if I am doing something wrong or is this a general issue with Python 2 and Python 3?

Thanks a lot in advance,

Joachim

**Comment by nvictus** [comment]
Awesome! Glad to help you with cooler support. :)

I actually think I know where this is coming from. It's a bytes vs text issue. It should have been fixed in the latest release. Could you try again?

**Comment by joachimwolff** [comment]
I updated the bioconda recipe, it was still on 0.7.4. See, https://github.com/bioconda/bioconda-recipes/pull/6794

**Comment by nvictus** [comment]
Awesome! Thank you!

**Comment by joachimwolff** [comment]
Ok, it is solved with the 0.7.6 version. Important: You have to create the matrices again with this version. 
Thanks for your support @nvictus.
