### ISSUE TITLE
FTP server empty

### ISSUE THREAD

**Issue by joachimwolff** [mirnylab/cooler#97]
Dear cooler-team,

the listed ftp server (ftp://cooler.csail.mit.edu/coolers) is reachable but does not contain any files. If I try to download i.e. the file used in your notebooks (ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-GM12878-MboI-allreps-filtered.5kb.cool) it is not reachable.

Is this on purpose or can you fix it?

Thanks a lot,

Joachim

**Comment by nvictus** [comment]
Turns out there was a power outage yesterday and the volume hosting the cool files got unmounted. Fixed!

**Comment by joachimwolff** [comment]
@nvictus Thank you. :+1:

**Comment by jolo2486** [comment]
Same here; I cannot find the file `Rao2014-GM12878-MboI-allreps-filtered.5kb.cool` and it seems the folder `coolers/` is empty.
