### ISSUE TITLE
Warning: Argmax deprecated 

### ISSUE THREAD

**Issue by aakashsur** [mirnylab/cooler#99]
Hi, I got a warning:
```
/usr/local/lib/python2.7/dist-packages/cooler/_binning.py:81: FutureWarning: 'argmax' is deprecated. Use 'idxmax' instead. The behavior of 'argmax' will be corrected to return the posi
tional maximum in the future. Use 'series.values.argmax' to get the position of the maximum now.
  chrmax = loadings.argmax()
```
I assume this is related to numpy/pandas, but I couldn't tell, not sure if it will make any impact, but I thought I would mention it.

**Comment by nvictus** [comment]
Thanks! I've noticed it recently too. It's a warning for future pandas behavior, so we'll make sure to fix it in the next release.

**Comment by nvictus** [comment]
Done!
